ReportDate[566] =	{"Date":"2021-10-11",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":1386,"Deaths":9,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":69552,"Deaths":498,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":215,"Deaths":0,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":2067,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":913,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":236,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":55936,"Deaths":921,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1110,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":166365,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":171570,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":142195,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":101834,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":175673,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":153609,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":70329,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":35225,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":65108,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":24989,"Deaths":25695,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":49193,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":110472,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":87944,"Deaths":1840,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":238918,"Deaths":6244,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":123104,"Deaths":1986,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":426946,"Deaths":13747,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1237779,"Deaths":26925,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":941602,"Deaths":24310,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":507407,"Deaths":10621,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":595089,"Deaths":12674,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":880471,"Deaths":23794,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":357961,"Deaths":10201,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":537240,"Deaths":13604,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":374495,"Deaths":9600,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2159712,"Deaths":55006,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":593612,"Deaths":16691,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":443181,"Deaths":9351,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1528963,"Deaths":39562,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":624349,"Deaths":19850,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":321611,"Deaths":7038,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":369859,"Deaths":7350,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1448779,"Deaths":35049,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1301362,"Deaths":67188,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":266780,"Deaths":6544,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":126273,"Deaths":2006,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1201201,"Deaths":19412,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4383780,"Deaths":150789,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":278242,"Deaths":6018,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":226078,"Deaths":3813,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":308275,"Deaths":2830,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":192491,"Deaths":2001,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":61385,"Deaths":1217,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":5258,"Deaths":75,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":1848,"Deaths":11,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":1456,"Deaths":6,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":6918,"Deaths":98,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":671,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":599859,"Deaths":9840,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":302,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":416266,"Deaths":11420,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":72458,"Deaths":751,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":796,"Deaths":10,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":61788,"Deaths":1251,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":98516,"Deaths":1514,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":27505,"Deaths":535,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":27511,"Deaths":356,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":8386,"Deaths":79,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":151923,"Deaths":2693,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":49100,"Deaths":1029,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":89240,"Deaths":1408,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":49492,"Deaths":696,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29256,"Deaths":499,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":102316,"Deaths":1784,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":697084,"Deaths":19244,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":36213,"Deaths":646,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":69094,"Deaths":1554,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":41810,"Deaths":810,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":49,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":124100,"Deaths":3473,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1008,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1126,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":603,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1293,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":199,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3195,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":306,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":147,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1318,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":1711,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1544,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12268,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68299,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1191,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":421,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1600,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":937,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":577,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":461,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":18,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":677,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":954,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2658,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":260,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1214,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":494,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":981,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1523,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1452,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6834,"Deaths":255,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":750118,"Deaths":16162,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":13403,"Deaths":460,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":324352,"Deaths":9486,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":156899,"Deaths":2970,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":105457,"Deaths":2552,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":100490,"Deaths":2263,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1451584,"Deaths":27507,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":22878,"Deaths":937,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":35570,"Deaths":925,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":55944,"Deaths":1542,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":89321,"Deaths":2493,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16399,"Deaths":398,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":104004,"Deaths":3738,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":263936,"Deaths":6804,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2295,"Deaths":29,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5136,"Deaths":95,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":88300,"Deaths":3141,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":42662,"Deaths":1340,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":94983,"Deaths":3338,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":89124,"Deaths":2252,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":89656,"Deaths":3022,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":91079,"Deaths":4276,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":16336,"Deaths":668,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":56386,"Deaths":1741,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":87731,"Deaths":2224,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":6896,"Deaths":136,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":225582,"Deaths":7295,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":59122,"Deaths":1623,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":107450,"Deaths":3661,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":408712,"Deaths":12956,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1750,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":2936,"Deaths":53,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":1301,"Deaths":2,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":623,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":42157,"Deaths":281,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":45359,"Deaths":629,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":53544,"Deaths":785,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":41846,"Deaths":645,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":20385,"Deaths":180,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":9186,"Deaths":201,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":53963,"Deaths":369,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1649,"Deaths":6,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":32,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":3819,"Deaths":55,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":587496,"Deaths":10778,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":748997,"Deaths":15789,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":210937,"Deaths":3655,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":118136,"Deaths":3866,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":33923,"Deaths":520,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":93434,"Deaths":1754,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":339298,"Deaths":7785,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":50083,"Deaths":1207,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":305790,"Deaths":6004,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":973775,"Deaths":17953,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":184265,"Deaths":4020,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":48108,"Deaths":1057,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":302803,"Deaths":10236,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":105827,"Deaths":3554,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":77511,"Deaths":1700,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":138528,"Deaths":4430,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":4435,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7634,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2057562,"Deaths":14256,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":54924,"Deaths":280,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":605239,"Deaths":5931,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":725998,"Deaths":9661,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":65280,"Deaths":820,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1005554,"Deaths":13570,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10674,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1439218,"Deaths":25089,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":177148,"Deaths":3330,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":826162,"Deaths":10086,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":771000,"Deaths":9875,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":220618,"Deaths":3706,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":330586,"Deaths":4426,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":348365,"Deaths":5135,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":2981400,"Deaths":37895,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":4801796,"Deaths":26342,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":20853,"Deaths":208,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10365,"Deaths":51,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":792635,"Deaths":10523,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6579608,"Deaths":139578,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":122108,"Deaths":1885,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":82487,"Deaths":1423,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":107566,"Deaths":363,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":31473,"Deaths":671,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1032144,"Deaths":8255,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":127095,"Deaths":1848,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":601894,"Deaths":16531,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":954366,"Deaths":8954,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":31677,"Deaths":388,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2679568,"Deaths":35796,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":668070,"Deaths":3932,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":84270,"Deaths":816,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1709965,"Deaths":22896,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":343675,"Deaths":7396,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1576943,"Deaths":18914,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":81630,"Deaths":2549,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":30444,"Deaths":619,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":84932,"Deaths":1425,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":459211,"Deaths":7987,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":426620,"Deaths":13514,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":114405,"Deaths":3828,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":387399,"Deaths":8690,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":113371,"Deaths":4416,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":886894,"Deaths":34090,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":114549,"Deaths":3082,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":14546,"Deaths":497,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":77479,"Deaths":1197,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":48652,"Deaths":1375,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":380686,"Deaths":11779,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":269834,"Deaths":6803,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":75664,"Deaths":1652,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":301889,"Deaths":6897,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":284620,"Deaths":7212,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":64128,"Deaths":1455,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":12207,"Deaths":474,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":472672,"Deaths":11794,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":106220,"Deaths":1148,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1893,"Deaths":27,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":5778,"Deaths":38,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":100089,"Deaths":1007,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":5276,"Deaths":82,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":3085,"Deaths":37,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":74276,"Deaths":619,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":9466,"Deaths":174,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":18618,"Deaths":216,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":16690,"Deaths":174,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":21828,"Deaths":199,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":60437,"Deaths":1469,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":78176,"Deaths":1391,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":24337,"Deaths":218,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":7929,"Deaths":128,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3487,"Deaths":53,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":4693,"Deaths":38,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":9078,"Deaths":67,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":168529,"Deaths":1287,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4124,"Deaths":31,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":14361,"Deaths":136,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":35805,"Deaths":287,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":14711,"Deaths":164,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":16292,"Deaths":117,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":6131,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":8806,"Deaths":96,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":6048,"Deaths":73,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":15493,"Deaths":150,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":7962,"Deaths":61,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":8187,"Deaths":84,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":15185,"Deaths":136,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":49994,"Deaths":346,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":201222,"Deaths":3005,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4325,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":5816,"Deaths":29,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":115369,"Deaths":1015,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":12347,"Deaths":102,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":1645,"Deaths":4,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":26726,"Deaths":209,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":15397,"Deaths":116,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3278,"Deaths":65,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":376893,"Deaths":3034,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1655,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":4843,"Deaths":51,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":5279,"Deaths":62,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":3543,"Deaths":57,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":5649,"Deaths":91,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":5148,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":206146,"Deaths":3440,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":140825,"Deaths":1906,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":126380,"Deaths":907,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":60994,"Deaths":871,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":99244,"Deaths":1206,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":70877,"Deaths":616,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":109533,"Deaths":969,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":4659,"Deaths":90,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":137320,"Deaths":1487,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":206048,"Deaths":2350,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":225676,"Deaths":999,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":691003,"Deaths":9481,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":62604,"Deaths":408,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":188523,"Deaths":2521,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":9987,"Deaths":149,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":6484,"Deaths":22,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":34514,"Deaths":2785,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":63092,"Deaths":9489,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":55579,"Deaths":2328,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":23351,"Deaths":2000,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":22678,"Deaths":2241,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":66389,"Deaths":7973,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":957184,"Deaths":39471,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":90523,"Deaths":7235,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":32498,"Deaths":1944,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":47883,"Deaths":2984,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":179933,"Deaths":12248,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":75413,"Deaths":5996,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":61020,"Deaths":7621,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":157471,"Deaths":16503,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":367552,"Deaths":43335,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":71901,"Deaths":7780,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":49007,"Deaths":4638,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":33325,"Deaths":2714,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":199938,"Deaths":12690,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":79102,"Deaths":5316,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":121740,"Deaths":14795,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":94912,"Deaths":5381,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":58629,"Deaths":3993,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":100829,"Deaths":6469,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":72445,"Deaths":8562,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":109492,"Deaths":8305,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":138345,"Deaths":5305,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":99097,"Deaths":6550,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":28834,"Deaths":2906,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":120047,"Deaths":14046,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":71560,"Deaths":5346,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":40959,"Deaths":3278,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":15645,"Deaths":170,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":2257,"Deaths":19,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":16804,"Deaths":168,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":40060,"Deaths":359,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":45192,"Deaths":252,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":54853,"Deaths":488,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":224122,"Deaths":2105,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":51506,"Deaths":268,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":134119,"Deaths":1704,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":316298,"Deaths":3177,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":347473,"Deaths":2733,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":131349,"Deaths":1166,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":4403,"Deaths":69,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":6489,"Deaths":15,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":157099,"Deaths":1305,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":34786,"Deaths":258,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":483056,"Deaths":4379,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":34354,"Deaths":739,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":33083,"Deaths":350,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10353,"Deaths":186,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":106201,"Deaths":933,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":176048,"Deaths":5650,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":436442,"Deaths":12792,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":463167,"Deaths":7502,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":31619,"Deaths":1254,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":77328,"Deaths":6651,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":26118,"Deaths":1503,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":114929,"Deaths":9665,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":33838,"Deaths":2105,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":65803,"Deaths":4123,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":100805,"Deaths":9957,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":73565,"Deaths":4763,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":16168,"Deaths":1152,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":35562,"Deaths":2693,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":58855,"Deaths":8340,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":86134,"Deaths":7001,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":88259,"Deaths":10168,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":61472,"Deaths":8595,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":952334,"Deaths":88515,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":45056,"Deaths":4173,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":13862,"Deaths":768,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":29598,"Deaths":1514,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":15790,"Deaths":1046,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":87719,"Deaths":11954,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":40158,"Deaths":4128,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":48652,"Deaths":3000,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":29784,"Deaths":1949,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":18765,"Deaths":1563,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":32091,"Deaths":3092,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":412,"Deaths":31,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":20208,"Deaths":467,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":80739,"Deaths":4419,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":21946,"Deaths":374,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":36872,"Deaths":464,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":92805,"Deaths":1201,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":61449,"Deaths":1751,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":72879,"Deaths":1913,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":56264,"Deaths":1218,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":68427,"Deaths":1577,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":60030,"Deaths":1886,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":23382,"Deaths":635,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":100364,"Deaths":3682,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":2022,"Deaths":18,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":35009,"Deaths":2452,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":53158,"Deaths":2586,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":22230,"Deaths":341,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":113285,"Deaths":4944,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":51039,"Deaths":1676,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":8425,"Deaths":274,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":32835,"Deaths":833,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":57821,"Deaths":802,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":31106,"Deaths":625,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":49675,"Deaths":758,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":20170,"Deaths":385,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":26083,"Deaths":667,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":68352,"Deaths":907,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":58606,"Deaths":1356,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":87189,"Deaths":841,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":40288,"Deaths":1168,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":77310,"Deaths":1138,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":59267,"Deaths":552,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":72975,"Deaths":1836,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":35184,"Deaths":823,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":76373,"Deaths":6583,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":120306,"Deaths":6071,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":35013,"Deaths":744,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":60197,"Deaths":1502,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":71953,"Deaths":2493,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":55835,"Deaths":1777,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":11238,"Deaths":264,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":20414,"Deaths":629,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":29128,"Deaths":602,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1683677,"Deaths":29738,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":467399,"Deaths":8296,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":74441,"Deaths":2156,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":2444,"Deaths":48,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":176405,"Deaths":6972,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":23734,"Deaths":652,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":46047,"Deaths":463,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":65473,"Deaths":3127,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":88571,"Deaths":2286,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":48030,"Deaths":1023,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":81363,"Deaths":2161,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":73498,"Deaths":2978,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":107323,"Deaths":5173,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":71290,"Deaths":1187,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":52459,"Deaths":832,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":144305,"Deaths":7121,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":43952,"Deaths":1206,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":647623,"Deaths":22509,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":56632,"Deaths":1297,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":33610,"Deaths":318,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":112339,"Deaths":4132,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":92467,"Deaths":3332,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":52475,"Deaths":1795,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":89805,"Deaths":3356,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":144886,"Deaths":6773,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":44938,"Deaths":966,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":27936,"Deaths":796,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":44715,"Deaths":573,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":56181,"Deaths":3147,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":69587,"Deaths":1704,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":64547,"Deaths":2031,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":27278,"Deaths":282,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":56290,"Deaths":2284,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":86809,"Deaths":2734,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":56822,"Deaths":2048,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":96084,"Deaths":3035,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":71734,"Deaths":1995,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":139956,"Deaths":4572,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":51626,"Deaths":707,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":63886,"Deaths":1264,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":71071,"Deaths":1219,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":803876,"Deaths":11200,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":161616,"Deaths":3853,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":71003,"Deaths":2070,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":99803,"Deaths":965,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":511551,"Deaths":7784,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":95830,"Deaths":1001,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":46453,"Deaths":608,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":238933,"Deaths":6475,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":299890,"Deaths":7321,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":921841,"Deaths":15758,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":7570,"Deaths":128,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":102763,"Deaths":1993,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":186863,"Deaths":2639,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":39542,"Deaths":823,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":893471,"Deaths":16145,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":11038,"Deaths":108,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":141310,"Deaths":1739,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":82742,"Deaths":1248,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":261353,"Deaths":4969,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":13419,"Deaths":130,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":28551,"Deaths":354,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":37177,"Deaths":561,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4568,"Deaths":54,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":43108,"Deaths":328,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":13144,"Deaths":128,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":45480,"Deaths":561,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":25378,"Deaths":249,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":23478,"Deaths":324,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":27612,"Deaths":287,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":34064,"Deaths":351,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":44527,"Deaths":656,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":164933,"Deaths":1782,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":27184,"Deaths":482,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":275975,"Deaths":4433,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":42427,"Deaths":547,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":21469,"Deaths":223,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":25751,"Deaths":193,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":27546,"Deaths":481,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":29788,"Deaths":359,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":202243,"Deaths":2422,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":90514,"Deaths":1407,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":63817,"Deaths":1472,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":94993,"Deaths":2149,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":84286,"Deaths":2687,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":159155,"Deaths":5047,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":109066,"Deaths":2752,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":94406,"Deaths":2254,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":177984,"Deaths":4166,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":47129,"Deaths":1392,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":100412,"Deaths":2107,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":240256,"Deaths":5551,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":137997,"Deaths":2946,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":22480,"Deaths":909,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":37986,"Deaths":1198,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":158433,"Deaths":4053,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":77095,"Deaths":2017,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":163243,"Deaths":3454,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":85404,"Deaths":1985,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":88736,"Deaths":1338,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":32929,"Deaths":1163,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":88652,"Deaths":1501,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":80337,"Deaths":1384,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":77716,"Deaths":1838,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":69139,"Deaths":1300,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":64954,"Deaths":1658,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":120786,"Deaths":2773,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":99399,"Deaths":2049,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":594,"Deaths":1,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":5501,"Deaths":89,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2725,"Deaths":37,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":983,"Deaths":2,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":11968,"Deaths":100,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":6967915,"Deaths":120405,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":68,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":5655,"Deaths":97,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":8121,"Deaths":54,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":41,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":250930,"Deaths":2593,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":592721,"Deaths":8792,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":2898,"Deaths":23,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":382203,"Deaths":5973,"Recovered":"" }
		]}
