ReportDate[7] =	{"Date":"2020-03-29",
		"Data":[
		{"Prov":"Alberta","Region":"Canada","Cases":621,"Deaths":2,"Recovered":0 },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":2,"Deaths":0,"Recovered":0 },
		{"Prov":"Anhui","Region":"China","Cases":990,"Deaths":6,"Recovered":984 },
		{"Prov":"Aruba","Region":"Netherlands","Cases":50,"Deaths":0,"Recovered":1 },
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":77,"Deaths":0,"Recovered":2 },
		{"Prov":"Beijing","Region":"China","Cases":577,"Deaths":8,"Recovered":412 },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":22,"Deaths":0,"Recovered":2 },
		{"Prov":"British Columbia","Region":"Canada","Cases":884,"Deaths":17,"Recovered":0 },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2,"Deaths":0,"Recovered":0 },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":8,"Deaths":1,"Recovered":0 },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":108,"Deaths":2,"Recovered":0 },
		{"Prov":"Chongqing","Region":"China","Cases":579,"Deaths":6,"Recovered":570 },
		{"Prov":"Curacao","Region":"Netherlands","Cases":8,"Deaths":1,"Recovered":2 },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":0 },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":159,"Deaths":0,"Recovered":70 },
		{"Prov":"French Guiana","Region":"France","Cases":28,"Deaths":0,"Recovered":6 },
		{"Prov":"French Polynesia","Region":"France","Cases":30,"Deaths":0,"Recovered":0 },
		{"Prov":"Fujian","Region":"China","Cases":338,"Deaths":1,"Recovered":295 },
		{"Prov":"Gansu","Region":"China","Cases":138,"Deaths":2,"Recovered":125 },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":65,"Deaths":0,"Recovered":14 },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":0 },
		{"Prov":"Greenland","Region":"Denmark","Cases":10,"Deaths":0,"Recovered":2 },
		{"Prov":"Guadeloupe","Region":"France","Cases":106,"Deaths":4,"Recovered":17 },
		{"Prov":"Guangdong","Region":"China","Cases":1475,"Deaths":8,"Recovered":1349 },
		{"Prov":"Guangxi","Region":"China","Cases":254,"Deaths":2,"Recovered":250 },
		{"Prov":"Guizhou","Region":"China","Cases":146,"Deaths":2,"Recovered":144 },
		{"Prov":"Hainan","Region":"China","Cases":168,"Deaths":6,"Recovered":168 },
		{"Prov":"Hebei","Region":"China","Cases":319,"Deaths":6,"Recovered":310 },
		{"Prov":"Heilongjiang","Region":"China","Cases":484,"Deaths":13,"Recovered":469 },
		{"Prov":"Henan","Region":"China","Cases":1276,"Deaths":22,"Recovered":1251 },
		{"Prov":"Hong Kong","Region":"China","Cases":641,"Deaths":4,"Recovered":112 },
		{"Prov":"Hubei","Region":"China","Cases":67801,"Deaths":3182,"Recovered":62570 },
		{"Prov":"Hunan","Region":"China","Cases":1018,"Deaths":4,"Recovered":1014 },
		{"Prov":"Inner Mongolia","Region":"China","Cases":95,"Deaths":1,"Recovered":74 },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":42,"Deaths":0,"Recovered":0 },
		{"Prov":"Jiangsu","Region":"China","Cases":644,"Deaths":0,"Recovered":631 },
		{"Prov":"Jiangxi","Region":"China","Cases":937,"Deaths":1,"Recovered":934 },
		{"Prov":"Jilin","Region":"China","Cases":98,"Deaths":1,"Recovered":92 },
		{"Prov":"Liaoning","Region":"China","Cases":134,"Deaths":2,"Recovered":124 },
		{"Prov":"Macau","Region":"China","Cases":37,"Deaths":0,"Recovered":10 },
		{"Prov":"Manitoba","Region":"Canada","Cases":72,"Deaths":1,"Recovered":0 },
		{"Prov":"Martinique","Region":"France","Cases":93,"Deaths":1,"Recovered":0 },
		{"Prov":"Mayotte","Region":"France","Cases":63,"Deaths":0,"Recovered":0 },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":5,"Deaths":0,"Recovered":0 },
		{"Prov":"New Brunswick","Region":"Canada","Cases":66,"Deaths":0,"Recovered":0 },
		{"Prov":"New Caledonia","Region":"France","Cases":15,"Deaths":0,"Recovered":0 },
		{"Prov":"New South Wales","Region":"Australia","Cases":1791,"Deaths":8,"Recovered":4 },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":135,"Deaths":0,"Recovered":0 },
		{"Prov":"Ningxia","Region":"China","Cases":75,"Deaths":0,"Recovered":75 },
		{"Prov":"Northern Territory","Region":"Australia","Cases":15,"Deaths":0,"Recovered":0 },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":1,"Deaths":0,"Recovered":0 },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":122,"Deaths":0,"Recovered":0 },
		{"Prov":"Ontario","Region":"Canada","Cases":1355,"Deaths":21,"Recovered":0 },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":11,"Deaths":0,"Recovered":0 },
		{"Prov":"Qinghai","Region":"China","Cases":18,"Deaths":0,"Recovered":18 },
		{"Prov":"Quebec","Region":"Canada","Cases":2840,"Deaths":22,"Recovered":0 },
		{"Prov":"Queensland","Region":"Australia","Cases":656,"Deaths":2,"Recovered":8 },
		{"Prov":"Recovered","Region":"Canada","Cases":0,"Deaths":0,"Recovered":466 },
		{"Prov":"Reunion","Region":"France","Cases":183,"Deaths":0,"Recovered":1 },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":5,"Deaths":0,"Recovered":0 },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":156,"Deaths":0,"Recovered":0 },
		{"Prov":"Shaanxi","Region":"China","Cases":253,"Deaths":3,"Recovered":242 },
		{"Prov":"Shandong","Region":"China","Cases":772,"Deaths":7,"Recovered":752 },
		{"Prov":"Shanghai","Region":"China","Cases":492,"Deaths":5,"Recovered":334 },
		{"Prov":"Shanxi","Region":"China","Cases":136,"Deaths":0,"Recovered":133 },
		{"Prov":"Sichuan","Region":"China","Cases":550,"Deaths":3,"Recovered":536 },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":6,"Deaths":0,"Recovered":0 },
		{"Prov":"South Australia","Region":"Australia","Cases":299,"Deaths":0,"Recovered":6 },
		{"Prov":"St Martin","Region":"France","Cases":11,"Deaths":0,"Recovered":0 },
		{"Prov":"Tasmania","Region":"Australia","Cases":66,"Deaths":0,"Recovered":5 },
		{"Prov":"Tianjin","Region":"China","Cases":166,"Deaths":3,"Recovered":133 },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":1 },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":0 },
		{"Prov":"Victoria","Region":"Australia","Cases":769,"Deaths":4,"Recovered":191 },
		{"Prov":"Western Australia","Region":"Australia","Cases":311,"Deaths":2,"Recovered":28 },
		{"Prov":"Xinjiang","Region":"China","Cases":76,"Deaths":3,"Recovered":73 },
		{"Prov":"Yukon","Region":"Canada","Cases":4,"Deaths":0,"Recovered":0 },
		{"Prov":"Yunnan","Region":"China","Cases":180,"Deaths":2,"Recovered":172 },
		{"Prov":"Zhejiang","Region":"China","Cases":1254,"Deaths":1,"Recovered":1225 }
		]}
