ReportDate[47] =	{"Date":"2020-05-08",
		"Data":[
		{"Prov":"Alberta","Region":"Canada","Cases":6098,"Deaths":115,"Recovered":0 },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":3,"Deaths":0,"Recovered":3 },
		{"Prov":"Anhui","Region":"China","Cases":991,"Deaths":6,"Recovered":985 },
		{"Prov":"Aruba","Region":"Netherlands","Cases":101,"Deaths":3,"Recovered":89 },
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":107,"Deaths":3,"Recovered":103 },
		{"Prov":"Beijing","Region":"China","Cases":593,"Deaths":9,"Recovered":560 },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":118,"Deaths":7,"Recovered":61 },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":6,"Deaths":0,"Recovered":0 },
		{"Prov":"British Columbia","Region":"Canada","Cases":2315,"Deaths":127,"Recovered":0 },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":7,"Deaths":1,"Recovered":3 },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":81,"Deaths":1,"Recovered":41 },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":545,"Deaths":41,"Recovered":447 },
		{"Prov":"Chongqing","Region":"China","Cases":579,"Deaths":6,"Recovered":573 },
		{"Prov":"Curacao","Region":"Netherlands","Cases":16,"Deaths":1,"Recovered":14 },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":1,"Deaths":1,"Recovered":0 },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":13,"Deaths":0,"Recovered":13 },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":187,"Deaths":0,"Recovered":187 },
		{"Prov":"French Guiana","Region":"France","Cases":141,"Deaths":1,"Recovered":119 },
		{"Prov":"French Polynesia","Region":"France","Cases":60,"Deaths":0,"Recovered":56 },
		{"Prov":"Fujian","Region":"China","Cases":356,"Deaths":1,"Recovered":354 },
		{"Prov":"Gansu","Region":"China","Cases":139,"Deaths":2,"Recovered":137 },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":146,"Deaths":0,"Recovered":142 },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":0 },
		{"Prov":"Greenland","Region":"Denmark","Cases":11,"Deaths":0,"Recovered":11 },
		{"Prov":"Guadeloupe","Region":"France","Cases":154,"Deaths":13,"Recovered":104 },
		{"Prov":"Guangdong","Region":"China","Cases":1589,"Deaths":8,"Recovered":1575 },
		{"Prov":"Guangxi","Region":"China","Cases":254,"Deaths":2,"Recovered":252 },
		{"Prov":"Guizhou","Region":"China","Cases":147,"Deaths":2,"Recovered":145 },
		{"Prov":"Hainan","Region":"China","Cases":168,"Deaths":6,"Recovered":162 },
		{"Prov":"Hebei","Region":"China","Cases":328,"Deaths":6,"Recovered":320 },
		{"Prov":"Heilongjiang","Region":"China","Cases":944,"Deaths":13,"Recovered":815 },
		{"Prov":"Henan","Region":"China","Cases":1276,"Deaths":22,"Recovered":1254 },
		{"Prov":"Hong Kong","Region":"China","Cases":1044,"Deaths":4,"Recovered":960 },
		{"Prov":"Hubei","Region":"China","Cases":68128,"Deaths":4512,"Recovered":63616 },
		{"Prov":"Hunan","Region":"China","Cases":1019,"Deaths":4,"Recovered":1015 },
		{"Prov":"Inner Mongolia","Region":"China","Cases":201,"Deaths":1,"Recovered":172 },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":329,"Deaths":23,"Recovered":271 },
		{"Prov":"Jiangsu","Region":"China","Cases":653,"Deaths":0,"Recovered":652 },
		{"Prov":"Jiangxi","Region":"China","Cases":937,"Deaths":1,"Recovered":936 },
		{"Prov":"Jilin","Region":"China","Cases":113,"Deaths":1,"Recovered":104 },
		{"Prov":"Liaoning","Region":"China","Cases":146,"Deaths":2,"Recovered":144 },
		{"Prov":"Macau","Region":"China","Cases":45,"Deaths":0,"Recovered":40 },
		{"Prov":"Manitoba","Region":"Canada","Cases":284,"Deaths":7,"Recovered":0 },
		{"Prov":"Martinique","Region":"France","Cases":186,"Deaths":14,"Recovered":83 },
		{"Prov":"Mayotte","Region":"France","Cases":854,"Deaths":10,"Recovered":352 },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":11,"Deaths":1,"Recovered":8 },
		{"Prov":"New Brunswick","Region":"Canada","Cases":120,"Deaths":0,"Recovered":0 },
		{"Prov":"New Caledonia","Region":"France","Cases":18,"Deaths":0,"Recovered":18 },
		{"Prov":"New South Wales","Region":"Australia","Cases":3051,"Deaths":44,"Recovered":2504 },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":261,"Deaths":3,"Recovered":0 },
		{"Prov":"Ningxia","Region":"China","Cases":75,"Deaths":0,"Recovered":75 },
		{"Prov":"Northern Territory","Region":"Australia","Cases":29,"Deaths":0,"Recovered":27 },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":5,"Deaths":0,"Recovered":0 },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":1008,"Deaths":46,"Recovered":0 },
		{"Prov":"Ontario","Region":"Canada","Cases":20826,"Deaths":1665,"Recovered":0 },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":27,"Deaths":0,"Recovered":0 },
		{"Prov":"Qinghai","Region":"China","Cases":18,"Deaths":0,"Recovered":18 },
		{"Prov":"Quebec","Region":"Canada","Cases":36161,"Deaths":2726,"Recovered":0 },
		{"Prov":"Queensland","Region":"Australia","Cases":1045,"Deaths":6,"Recovered":1019 },
		{"Prov":"Recovered","Region":"Canada","Cases":0,"Deaths":0,"Recovered":30239 },
		{"Prov":"Reunion","Region":"France","Cases":426,"Deaths":0,"Recovered":354 },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":6,"Deaths":0,"Recovered":6 },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":1,"Deaths":0,"Recovered":0 },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":544,"Deaths":7,"Recovered":0 },
		{"Prov":"Shaanxi","Region":"China","Cases":308,"Deaths":3,"Recovered":268 },
		{"Prov":"Shandong","Region":"China","Cases":788,"Deaths":7,"Recovered":776 },
		{"Prov":"Shanghai","Region":"China","Cases":657,"Deaths":7,"Recovered":623 },
		{"Prov":"Shanxi","Region":"China","Cases":198,"Deaths":0,"Recovered":195 },
		{"Prov":"Sichuan","Region":"China","Cases":561,"Deaths":3,"Recovered":558 },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":76,"Deaths":14,"Recovered":44 },
		{"Prov":"South Australia","Region":"Australia","Cases":439,"Deaths":4,"Recovered":433 },
		{"Prov":"St Martin","Region":"France","Cases":38,"Deaths":3,"Recovered":30 },
		{"Prov":"Tasmania","Region":"Australia","Cases":227,"Deaths":13,"Recovered":175 },
		{"Prov":"Tianjin","Region":"China","Cases":191,"Deaths":3,"Recovered":186 },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":1 },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":12,"Deaths":1,"Recovered":8 },
		{"Prov":"Victoria","Region":"Australia","Cases":1468,"Deaths":18,"Recovered":1327 },
		{"Prov":"Western Australia","Region":"Australia","Cases":552,"Deaths":9,"Recovered":534 },
		{"Prov":"Xinjiang","Region":"China","Cases":76,"Deaths":3,"Recovered":73 },
		{"Prov":"Yukon","Region":"Canada","Cases":11,"Deaths":0,"Recovered":0 },
		{"Prov":"Yunnan","Region":"China","Cases":185,"Deaths":2,"Recovered":182 },
		{"Prov":"Zhejiang","Region":"China","Cases":1268,"Deaths":1,"Recovered":1267 }
		]}
