ReportDate[503] =	{"Date":"2021-08-09",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":124,"Deaths":3,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":11558,"Deaths":87,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":199,"Deaths":0,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":1926,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":868,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":235,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":21041,"Deaths":820,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1059,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":150785,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":143383,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":131174,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":89432,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":165047,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":134698,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":64356,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":32043,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":60963,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":22276,"Deaths":25274,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":44075,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":103147,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":87422,"Deaths":1804,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":231783,"Deaths":5905,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":121725,"Deaths":1926,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":419744,"Deaths":13591,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1202820,"Deaths":25983,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":923331,"Deaths":23692,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":455682,"Deaths":9741,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":547282,"Deaths":11989,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":761655,"Deaths":21304,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":340477,"Deaths":9752,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":496059,"Deaths":12800,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":360499,"Deaths":9082,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":1998878,"Deaths":51343,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":575680,"Deaths":16169,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":425425,"Deaths":9065,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1403372,"Deaths":35928,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":595942,"Deaths":19028,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":311784,"Deaths":6877,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":361034,"Deaths":7188,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1381971,"Deaths":33588,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1061793,"Deaths":59990,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":259832,"Deaths":6407,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":121043,"Deaths":1890,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1124632,"Deaths":18204,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4119265,"Deaths":140809,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":275776,"Deaths":5938,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":212851,"Deaths":3569,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":237027,"Deaths":2328,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":152918,"Deaths":1777,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":57860,"Deaths":1184,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":2439,"Deaths":46,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":1443,"Deaths":7,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":130,"Deaths":0,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":5907,"Deaths":93,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":657,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":560401,"Deaths":9359,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":212,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":379439,"Deaths":11242,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":50614,"Deaths":582,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":633,"Deaths":8,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":60025,"Deaths":1218,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":97247,"Deaths":1431,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":26460,"Deaths":515,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":26871,"Deaths":336,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":8078,"Deaths":72,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":149194,"Deaths":2570,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":47915,"Deaths":964,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":87857,"Deaths":1368,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":48810,"Deaths":640,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29167,"Deaths":490,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":100192,"Deaths":1710,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":677525,"Deaths":18551,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":35484,"Deaths":627,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":67673,"Deaths":1496,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":40597,"Deaths":794,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":51,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":121170,"Deaths":3325,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1008,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1102,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":603,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":754,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":199,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":2931,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":277,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":147,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1317,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":1612,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1462,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12015,"Deaths":212,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68250,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1162,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":410,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1407,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":937,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":574,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":438,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":63,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":18,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":665,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":908,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2369,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":254,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1168,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":435,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":980,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":914,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1400,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6676,"Deaths":251,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":723128,"Deaths":15521,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":12910,"Deaths":426,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":310373,"Deaths":9267,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":152580,"Deaths":2893,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":103695,"Deaths":2490,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":98967,"Deaths":2194,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1427741,"Deaths":26964,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":22384,"Deaths":893,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":34705,"Deaths":888,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":53435,"Deaths":1400,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":87183,"Deaths":2425,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16135,"Deaths":384,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":101284,"Deaths":3591,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":259698,"Deaths":6650,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2218,"Deaths":29,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5057,"Deaths":91,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":86690,"Deaths":3015,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":41699,"Deaths":1308,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":89879,"Deaths":3223,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":86414,"Deaths":2169,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":87583,"Deaths":2915,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":87568,"Deaths":4077,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":15705,"Deaths":642,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":55001,"Deaths":1680,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":86298,"Deaths":2164,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":6763,"Deaths":133,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":221419,"Deaths":7109,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":58084,"Deaths":1574,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":106020,"Deaths":3535,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":391120,"Deaths":12338,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1733,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":2862,"Deaths":49,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":987,"Deaths":2,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":182,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":30875,"Deaths":193,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":23902,"Deaths":166,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":21125,"Deaths":283,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":26747,"Deaths":167,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":19546,"Deaths":175,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":134,"Deaths":0,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":40245,"Deaths":288,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1336,"Deaths":2,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":28,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":2713,"Deaths":39,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":445,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":508194,"Deaths":10432,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":656286,"Deaths":15363,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":184581,"Deaths":3585,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":109645,"Deaths":3818,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":28092,"Deaths":493,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":80411,"Deaths":1630,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":296532,"Deaths":7597,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":44757,"Deaths":1184,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":266935,"Deaths":5819,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":835008,"Deaths":17308,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":158593,"Deaths":3912,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":42474,"Deaths":1030,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":287083,"Deaths":10140,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":99795,"Deaths":3473,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":66876,"Deaths":1640,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":129407,"Deaths":4386,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":5400,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7546,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":1983721,"Deaths":13549,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":50372,"Deaths":246,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":575220,"Deaths":5404,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":725235,"Deaths":9646,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":61984,"Deaths":811,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1003244,"Deaths":13540,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10653,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1436800,"Deaths":25067,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":171944,"Deaths":3164,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":825064,"Deaths":10077,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":770091,"Deaths":9650,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":208197,"Deaths":3535,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":322658,"Deaths":4390,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":347406,"Deaths":5130,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":2919711,"Deaths":36817,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":3565574,"Deaths":17852,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":20400,"Deaths":207,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10249,"Deaths":50,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":791970,"Deaths":10514,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6357833,"Deaths":134064,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":104791,"Deaths":1657,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":69358,"Deaths":1174,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":45457,"Deaths":169,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":28709,"Deaths":585,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":987956,"Deaths":6501,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":121665,"Deaths":1800,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":599514,"Deaths":16320,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":953840,"Deaths":8954,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":27908,"Deaths":355,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2577237,"Deaths":34340,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":649859,"Deaths":3828,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":80416,"Deaths":771,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1708793,"Deaths":22774,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":342423,"Deaths":7368,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1534360,"Deaths":18240,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":76906,"Deaths":2515,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":27759,"Deaths":592,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":72255,"Deaths":1268,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":434981,"Deaths":7617,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":399704,"Deaths":13290,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":108715,"Deaths":3791,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":363442,"Deaths":8425,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":106462,"Deaths":4368,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":858260,"Deaths":33839,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":106921,"Deaths":3041,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":14001,"Deaths":492,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":73978,"Deaths":1184,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":46639,"Deaths":1363,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":367468,"Deaths":11701,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":257900,"Deaths":6674,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":64826,"Deaths":1516,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":249561,"Deaths":6088,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":257588,"Deaths":6932,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":59285,"Deaths":1424,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":11852,"Deaths":473,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":442114,"Deaths":11649,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":57002,"Deaths":1013,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1096,"Deaths":21,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":2883,"Deaths":32,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":57350,"Deaths":737,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":3203,"Deaths":77,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":1882,"Deaths":36,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":45097,"Deaths":542,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":6568,"Deaths":162,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":10002,"Deaths":189,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":9898,"Deaths":156,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":12909,"Deaths":180,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":47075,"Deaths":1428,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":47658,"Deaths":1320,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":14573,"Deaths":172,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":5810,"Deaths":120,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":2179,"Deaths":47,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":2600,"Deaths":32,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":4487,"Deaths":42,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":98992,"Deaths":1009,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":2189,"Deaths":29,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":7913,"Deaths":122,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":20538,"Deaths":249,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":6344,"Deaths":115,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":10666,"Deaths":91,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":3506,"Deaths":27,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":5730,"Deaths":94,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":3806,"Deaths":69,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":9634,"Deaths":134,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":4607,"Deaths":54,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":3981,"Deaths":64,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":9023,"Deaths":127,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":29155,"Deaths":241,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":123460,"Deaths":2733,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":3612,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":3019,"Deaths":25,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":67342,"Deaths":856,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":6756,"Deaths":94,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":822,"Deaths":2,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":12435,"Deaths":157,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":9421,"Deaths":89,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":1863,"Deaths":63,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":252237,"Deaths":2314,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1007,"Deaths":3,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":2623,"Deaths":38,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":3254,"Deaths":50,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":2408,"Deaths":48,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":3467,"Deaths":80,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":2902,"Deaths":21,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":28596,"Deaths":2504,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":53536,"Deaths":8941,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":50816,"Deaths":2059,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":15761,"Deaths":1511,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":16496,"Deaths":1833,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":61004,"Deaths":7676,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":817561,"Deaths":36171,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":75048,"Deaths":6588,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":18466,"Deaths":1307,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":39155,"Deaths":2573,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":141704,"Deaths":11215,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":56725,"Deaths":4992,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":46841,"Deaths":6534,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":113373,"Deaths":13434,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":304869,"Deaths":38842,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":56560,"Deaths":6300,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":38200,"Deaths":3690,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":22314,"Deaths":2124,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":151191,"Deaths":10328,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":57849,"Deaths":4233,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":94393,"Deaths":12588,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":75823,"Deaths":4625,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":46785,"Deaths":3418,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":75220,"Deaths":5564,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":60984,"Deaths":7233,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":91887,"Deaths":7135,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":92364,"Deaths":4498,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":75826,"Deaths":5575,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":22071,"Deaths":2622,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":86359,"Deaths":10972,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":56028,"Deaths":4651,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":34525,"Deaths":2954,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":12529,"Deaths":111,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":1725,"Deaths":17,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":14137,"Deaths":132,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":37112,"Deaths":353,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":40724,"Deaths":247,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":48711,"Deaths":484,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":208992,"Deaths":2040,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":47870,"Deaths":266,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":125533,"Deaths":1665,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":301660,"Deaths":3146,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":323750,"Deaths":2657,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":122015,"Deaths":1146,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":2950,"Deaths":34,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":5299,"Deaths":15,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":145736,"Deaths":1288,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":32444,"Deaths":250,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":447985,"Deaths":4314,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":27507,"Deaths":650,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":31234,"Deaths":332,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":8876,"Deaths":157,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":91217,"Deaths":821,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":149056,"Deaths":4570,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":365824,"Deaths":11239,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":401790,"Deaths":6235,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":30808,"Deaths":1215,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":74960,"Deaths":6555,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":25543,"Deaths":1468,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":111276,"Deaths":9493,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":32072,"Deaths":2059,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":64101,"Deaths":4030,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":98597,"Deaths":9848,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":70893,"Deaths":4633,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":15695,"Deaths":1131,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":34806,"Deaths":2654,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":56791,"Deaths":8185,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":82091,"Deaths":6876,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":85802,"Deaths":10044,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":60013,"Deaths":8496,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":926866,"Deaths":87526,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":44394,"Deaths":4137,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":13692,"Deaths":753,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":28549,"Deaths":1468,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":15255,"Deaths":1022,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":84755,"Deaths":11763,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":37388,"Deaths":3948,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":47630,"Deaths":2931,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":29194,"Deaths":1932,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":17988,"Deaths":1541,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":31902,"Deaths":3052,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":4787,"Deaths":269,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":16809,"Deaths":303,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":64575,"Deaths":3121,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":19846,"Deaths":279,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":28966,"Deaths":356,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":75921,"Deaths":1088,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":45961,"Deaths":1199,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":50612,"Deaths":847,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":45911,"Deaths":934,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":56296,"Deaths":876,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":53897,"Deaths":1739,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":17080,"Deaths":368,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":76661,"Deaths":2305,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":1259,"Deaths":9,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":29972,"Deaths":1797,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":43512,"Deaths":1882,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":18147,"Deaths":234,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":89015,"Deaths":3958,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":42468,"Deaths":1413,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":6086,"Deaths":188,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":27793,"Deaths":623,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":44820,"Deaths":581,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":25832,"Deaths":496,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":42335,"Deaths":509,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":17271,"Deaths":242,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":22901,"Deaths":348,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":57313,"Deaths":739,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":47661,"Deaths":1024,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":68285,"Deaths":654,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":31858,"Deaths":810,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":67024,"Deaths":984,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":51412,"Deaths":446,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":57686,"Deaths":1274,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":28409,"Deaths":628,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":61399,"Deaths":4499,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":95207,"Deaths":4656,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":26939,"Deaths":520,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":48175,"Deaths":1147,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":58217,"Deaths":2233,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":41887,"Deaths":1221,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":9746,"Deaths":177,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":16627,"Deaths":412,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":24494,"Deaths":427,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1529350,"Deaths":26248,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":398698,"Deaths":7462,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":64008,"Deaths":1638,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":1684,"Deaths":17,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":145456,"Deaths":5300,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":19332,"Deaths":282,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":37685,"Deaths":265,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":54495,"Deaths":2427,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":64722,"Deaths":1722,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":40981,"Deaths":880,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":59427,"Deaths":1342,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":58315,"Deaths":1793,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":77310,"Deaths":3489,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":56888,"Deaths":959,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":44656,"Deaths":599,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":113739,"Deaths":5386,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":36279,"Deaths":837,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":545893,"Deaths":19708,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":45878,"Deaths":928,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":28398,"Deaths":157,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":80490,"Deaths":2779,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":75394,"Deaths":1897,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":42704,"Deaths":1372,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":67547,"Deaths":1965,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":112093,"Deaths":4553,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":38525,"Deaths":721,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":24387,"Deaths":633,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":38265,"Deaths":520,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":48613,"Deaths":2518,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":55887,"Deaths":1367,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":49120,"Deaths":1065,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":22690,"Deaths":237,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":41540,"Deaths":1266,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":68031,"Deaths":2062,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":45065,"Deaths":1513,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":74164,"Deaths":1954,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":56799,"Deaths":1446,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":108321,"Deaths":3604,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":44816,"Deaths":515,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":51515,"Deaths":895,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":58750,"Deaths":993,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":742468,"Deaths":10310,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":151812,"Deaths":3617,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":68324,"Deaths":2020,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":88572,"Deaths":875,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":480877,"Deaths":7495,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":85680,"Deaths":860,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":41512,"Deaths":582,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":218471,"Deaths":6032,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":284291,"Deaths":7040,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":858718,"Deaths":14920,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":6533,"Deaths":117,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":92360,"Deaths":1835,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":169229,"Deaths":2480,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":37184,"Deaths":802,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":842119,"Deaths":15616,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":10024,"Deaths":99,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":130586,"Deaths":1630,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":78417,"Deaths":1196,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":240593,"Deaths":4599,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":12939,"Deaths":130,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":27207,"Deaths":344,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":36116,"Deaths":560,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4257,"Deaths":52,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":41479,"Deaths":320,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":12651,"Deaths":121,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":43890,"Deaths":554,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":24480,"Deaths":246,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":22609,"Deaths":318,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":26906,"Deaths":274,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":32418,"Deaths":342,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":42764,"Deaths":637,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":158152,"Deaths":1761,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":26131,"Deaths":477,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":259888,"Deaths":4369,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":40862,"Deaths":540,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":20624,"Deaths":214,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":23804,"Deaths":181,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":27026,"Deaths":481,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":27896,"Deaths":353,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":192439,"Deaths":2383,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":82365,"Deaths":1324,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":57914,"Deaths":1353,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":80348,"Deaths":1799,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":63233,"Deaths":1882,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":136920,"Deaths":4534,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":92025,"Deaths":2406,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":86991,"Deaths":2108,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":149930,"Deaths":3617,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":36845,"Deaths":1187,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":89446,"Deaths":1895,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":220207,"Deaths":5245,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":128442,"Deaths":2773,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":20783,"Deaths":860,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":27381,"Deaths":980,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":138471,"Deaths":3701,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":70541,"Deaths":1869,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":142489,"Deaths":3023,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":78442,"Deaths":1874,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":79806,"Deaths":1208,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":22482,"Deaths":908,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":78686,"Deaths":1345,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":70463,"Deaths":1205,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":71761,"Deaths":1709,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":62340,"Deaths":1205,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":62301,"Deaths":1611,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":105548,"Deaths":2458,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":89006,"Deaths":1811,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":113,"Deaths":0,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":2614,"Deaths":33,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2532,"Deaths":37,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":646,"Deaths":2,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":9687,"Deaths":91,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":5324191,"Deaths":114508,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":66,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":5136,"Deaths":95,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":5587,"Deaths":33,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":22,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":167095,"Deaths":2228,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":355388,"Deaths":7992,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":2523,"Deaths":18,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":247569,"Deaths":5629,"Recovered":"" }
		]}
