ReportDate[587] =	{"Date":"2021-11-01",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":1788,"Deaths":13,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":75578,"Deaths":576,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":225,"Deaths":0,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":2090,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":918,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":237,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":91217,"Deaths":1134,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1112,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":181125,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":182835,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":150993,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":110378,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":183767,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":166293,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":77247,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":38047,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":69753,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":26162,"Deaths":25994,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":53895,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":120155,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":88050,"Deaths":1845,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":240306,"Deaths":6294,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":123637,"Deaths":1993,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":427806,"Deaths":13771,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1246439,"Deaths":27080,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":943675,"Deaths":24497,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":515134,"Deaths":10886,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":607488,"Deaths":12921,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":905247,"Deaths":24200,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":361099,"Deaths":10238,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":543550,"Deaths":13681,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":376501,"Deaths":9646,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2185536,"Deaths":55588,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":598422,"Deaths":16746,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":446066,"Deaths":9423,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1556474,"Deaths":40517,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":632011,"Deaths":20025,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":325812,"Deaths":7101,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":373693,"Deaths":7399,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1467244,"Deaths":35500,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1322150,"Deaths":68370,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":270451,"Deaths":6570,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":127390,"Deaths":2029,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1217010,"Deaths":19673,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4406252,"Deaths":152019,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":278504,"Deaths":6031,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":228746,"Deaths":3879,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":324199,"Deaths":3111,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":206284,"Deaths":2181,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":63688,"Deaths":1248,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":6476,"Deaths":117,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":1994,"Deaths":16,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":1871,"Deaths":11,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":7413,"Deaths":101,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":674,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":608599,"Deaths":9927,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":315,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":426456,"Deaths":11496,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":77793,"Deaths":854,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":944,"Deaths":10,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":63088,"Deaths":1257,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":99142,"Deaths":1517,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":27939,"Deaths":538,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":27902,"Deaths":359,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":8531,"Deaths":79,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":153646,"Deaths":2704,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":50142,"Deaths":1037,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":90032,"Deaths":1413,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":49967,"Deaths":699,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29335,"Deaths":499,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":104172,"Deaths":1797,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":716440,"Deaths":19359,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":36735,"Deaths":648,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":70266,"Deaths":1568,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":42557,"Deaths":811,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":46,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":126846,"Deaths":3492,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1008,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1164,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":604,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1308,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":313,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3226,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":340,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":158,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1338,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":1822,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1559,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12347,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68309,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1197,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":600,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1600,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":941,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":577,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":466,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":111,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":25,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":697,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":985,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2740,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":260,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1225,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":505,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":981,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1569,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1495,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6842,"Deaths":256,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":756947,"Deaths":16305,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":13656,"Deaths":464,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":330296,"Deaths":9568,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":158071,"Deaths":2987,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":105725,"Deaths":2564,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":100767,"Deaths":2271,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1455250,"Deaths":27551,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":22932,"Deaths":939,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":35666,"Deaths":927,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":56196,"Deaths":1563,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":89924,"Deaths":2505,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16425,"Deaths":400,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":104183,"Deaths":3740,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":264421,"Deaths":6825,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2316,"Deaths":29,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5145,"Deaths":97,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":88444,"Deaths":3143,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":43288,"Deaths":1356,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":96617,"Deaths":3373,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":89694,"Deaths":2278,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":89872,"Deaths":3029,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":93143,"Deaths":4331,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":16500,"Deaths":672,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":56876,"Deaths":1761,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":87909,"Deaths":2233,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":7109,"Deaths":136,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":226522,"Deaths":7315,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":59255,"Deaths":1625,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":107592,"Deaths":3666,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":411651,"Deaths":13036,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1787,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":2956,"Deaths":53,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":2212,"Deaths":3,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":810,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":44629,"Deaths":308,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":45541,"Deaths":636,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":54288,"Deaths":815,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":43347,"Deaths":683,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":20555,"Deaths":185,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":10985,"Deaths":266,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":54668,"Deaths":374,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1659,"Deaths":6,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":32,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":3920,"Deaths":56,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":637267,"Deaths":11004,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":825577,"Deaths":16086,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":225044,"Deaths":3709,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":125353,"Deaths":3926,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":35470,"Deaths":532,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":99068,"Deaths":1822,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":356564,"Deaths":7862,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":53588,"Deaths":1252,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":321620,"Deaths":6089,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":1016517,"Deaths":18222,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":193827,"Deaths":4094,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":49990,"Deaths":1067,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":329374,"Deaths":10334,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":112942,"Deaths":3589,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":82287,"Deaths":1728,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":153593,"Deaths":4522,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":1192,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7654,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2066670,"Deaths":14377,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":55161,"Deaths":280,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":610941,"Deaths":6004,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":726102,"Deaths":9661,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":65354,"Deaths":820,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1006074,"Deaths":13578,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10682,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1439888,"Deaths":25091,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":178121,"Deaths":3364,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":826597,"Deaths":10090,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":771262,"Deaths":10049,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":224251,"Deaths":3758,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":332347,"Deaths":4436,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":348771,"Deaths":5138,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":2988521,"Deaths":38084,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":4973954,"Deaths":32049,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":20971,"Deaths":208,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10365,"Deaths":51,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":792862,"Deaths":10524,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6611887,"Deaths":140226,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":123787,"Deaths":1923,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":83685,"Deaths":1452,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":122354,"Deaths":435,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":31859,"Deaths":685,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1041773,"Deaths":8336,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":128056,"Deaths":1858,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":602420,"Deaths":16560,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":954436,"Deaths":8954,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":31984,"Deaths":396,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2703613,"Deaths":36136,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":671623,"Deaths":3958,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":84514,"Deaths":816,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1710161,"Deaths":22900,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":343904,"Deaths":7401,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1593633,"Deaths":19149,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":83034,"Deaths":2562,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":30778,"Deaths":624,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":87608,"Deaths":1451,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":467572,"Deaths":8063,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":432679,"Deaths":13595,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":117301,"Deaths":3856,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":395591,"Deaths":8799,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":114981,"Deaths":4426,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":894769,"Deaths":34162,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":116277,"Deaths":3107,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":14669,"Deaths":498,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":79110,"Deaths":1203,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":49396,"Deaths":1378,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":385055,"Deaths":11814,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":273009,"Deaths":6835,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":76208,"Deaths":1674,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":308527,"Deaths":7019,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":289841,"Deaths":7283,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":65246,"Deaths":1464,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":12310,"Deaths":474,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":480822,"Deaths":11833,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":106645,"Deaths":1156,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1908,"Deaths":27,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":5894,"Deaths":38,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":100295,"Deaths":1024,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":5382,"Deaths":82,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":3113,"Deaths":38,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":74436,"Deaths":621,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":9483,"Deaths":175,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":18792,"Deaths":218,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":16789,"Deaths":176,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":22069,"Deaths":202,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":60752,"Deaths":1471,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":78460,"Deaths":1395,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":24403,"Deaths":218,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":7963,"Deaths":129,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3486,"Deaths":53,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":4700,"Deaths":38,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":9101,"Deaths":66,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":168903,"Deaths":1308,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4165,"Deaths":32,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":14392,"Deaths":136,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":35884,"Deaths":291,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":14789,"Deaths":163,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":16266,"Deaths":118,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":6137,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":8873,"Deaths":96,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":6116,"Deaths":73,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":15602,"Deaths":149,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":7992,"Deaths":61,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":8186,"Deaths":84,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":15306,"Deaths":136,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":50226,"Deaths":387,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":202473,"Deaths":3047,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4434,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":5854,"Deaths":30,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":115609,"Deaths":1045,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":12408,"Deaths":103,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":1719,"Deaths":5,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":26746,"Deaths":209,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":15446,"Deaths":116,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3287,"Deaths":65,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":381664,"Deaths":3148,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1668,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":4867,"Deaths":52,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":5293,"Deaths":62,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":3548,"Deaths":56,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":5740,"Deaths":93,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":5155,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":218545,"Deaths":3659,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":149002,"Deaths":1983,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":139530,"Deaths":1027,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":65517,"Deaths":903,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":103098,"Deaths":1237,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":77189,"Deaths":659,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":116375,"Deaths":1118,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":5477,"Deaths":115,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":145165,"Deaths":1599,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":218342,"Deaths":2529,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":241524,"Deaths":1352,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":715563,"Deaths":9602,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":69885,"Deaths":463,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":193922,"Deaths":2559,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":10071,"Deaths":149,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":7063,"Deaths":21,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":35837,"Deaths":2868,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":69508,"Deaths":9745,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":56019,"Deaths":2367,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":23938,"Deaths":2050,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":23237,"Deaths":2267,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":68612,"Deaths":8073,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":971426,"Deaths":39859,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":93338,"Deaths":7398,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":33113,"Deaths":1988,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":48692,"Deaths":3027,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":188805,"Deaths":12576,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":76251,"Deaths":6130,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":61980,"Deaths":7754,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":161006,"Deaths":17104,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":374088,"Deaths":43899,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":72977,"Deaths":8030,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":49387,"Deaths":4729,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":33940,"Deaths":2803,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":204018,"Deaths":13003,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":81515,"Deaths":5462,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":123943,"Deaths":15308,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":97145,"Deaths":5513,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":59478,"Deaths":4044,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":103140,"Deaths":6586,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":73464,"Deaths":8723,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":112063,"Deaths":8474,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":142169,"Deaths":5464,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":101382,"Deaths":6786,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":29222,"Deaths":2944,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":122285,"Deaths":14537,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":73672,"Deaths":5488,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":41561,"Deaths":3366,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":15931,"Deaths":171,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":2444,"Deaths":19,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":17091,"Deaths":174,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":42457,"Deaths":367,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":47924,"Deaths":263,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":59046,"Deaths":496,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":240326,"Deaths":2139,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":53703,"Deaths":271,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":144948,"Deaths":1740,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":330738,"Deaths":3200,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":361588,"Deaths":2753,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":139979,"Deaths":1182,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":4498,"Deaths":75,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":7236,"Deaths":16,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":166201,"Deaths":1317,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":37516,"Deaths":261,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":508084,"Deaths":4418,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":34481,"Deaths":740,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":33267,"Deaths":356,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10390,"Deaths":186,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":106945,"Deaths":940,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":178135,"Deaths":5751,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":440378,"Deaths":12924,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":470421,"Deaths":7569,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":31792,"Deaths":1258,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":77754,"Deaths":6670,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":26268,"Deaths":1508,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":115310,"Deaths":9676,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":34071,"Deaths":2116,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":65991,"Deaths":4131,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":101260,"Deaths":9977,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":73992,"Deaths":4783,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":16238,"Deaths":1160,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":35662,"Deaths":2698,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":59196,"Deaths":8362,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":86683,"Deaths":7013,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":88926,"Deaths":10193,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":61879,"Deaths":8608,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":958685,"Deaths":88693,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":45108,"Deaths":4175,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":13907,"Deaths":773,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":29674,"Deaths":1515,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":15861,"Deaths":1049,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":88437,"Deaths":11989,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":40607,"Deaths":4161,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":48769,"Deaths":3006,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":29958,"Deaths":1951,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":18902,"Deaths":1563,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":32122,"Deaths":3090,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":5137,"Deaths":158,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":21640,"Deaths":565,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":89041,"Deaths":4943,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":22991,"Deaths":407,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":39939,"Deaths":481,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":100874,"Deaths":1263,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":66527,"Deaths":1998,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":86831,"Deaths":2658,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":62809,"Deaths":1315,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":76800,"Deaths":1894,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":63144,"Deaths":1987,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":25414,"Deaths":722,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":109603,"Deaths":4277,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":2390,"Deaths":21,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":37994,"Deaths":2779,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":56172,"Deaths":2761,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":23742,"Deaths":370,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":122225,"Deaths":5408,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":55563,"Deaths":1845,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":9293,"Deaths":293,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":35236,"Deaths":943,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":65037,"Deaths":867,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":32360,"Deaths":657,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":53142,"Deaths":854,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":21044,"Deaths":440,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":27593,"Deaths":761,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":74801,"Deaths":980,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":63624,"Deaths":1464,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":94574,"Deaths":911,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":44002,"Deaths":1339,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":82400,"Deaths":1355,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":63986,"Deaths":602,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":79346,"Deaths":1965,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":38845,"Deaths":874,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":81812,"Deaths":7423,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":131931,"Deaths":6589,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":38930,"Deaths":798,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":66552,"Deaths":1614,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":78759,"Deaths":2572,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":63017,"Deaths":2053,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":11761,"Deaths":280,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":22644,"Deaths":691,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":31926,"Deaths":720,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1824494,"Deaths":31438,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":521361,"Deaths":8806,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":79251,"Deaths":2330,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":2781,"Deaths":63,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":192029,"Deaths":7760,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":25630,"Deaths":701,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":50641,"Deaths":515,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":71301,"Deaths":3395,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":97663,"Deaths":2473,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":53540,"Deaths":1104,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":89798,"Deaths":2609,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":80559,"Deaths":3546,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":120490,"Deaths":5821,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":76523,"Deaths":1264,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":58032,"Deaths":915,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":156717,"Deaths":7778,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":48205,"Deaths":1423,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":711804,"Deaths":23965,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":62391,"Deaths":1450,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":35030,"Deaths":362,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":134692,"Deaths":4651,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":101998,"Deaths":3873,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":62349,"Deaths":1928,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":98213,"Deaths":4055,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":158094,"Deaths":7504,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":48571,"Deaths":1119,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":30960,"Deaths":988,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":48186,"Deaths":593,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":60346,"Deaths":3476,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":77087,"Deaths":1842,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":71120,"Deaths":2384,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":28667,"Deaths":283,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":64136,"Deaths":2635,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":96294,"Deaths":3053,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":63132,"Deaths":2244,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":104436,"Deaths":3578,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":78643,"Deaths":2205,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":155035,"Deaths":4956,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":54319,"Deaths":759,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":69240,"Deaths":1384,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":77233,"Deaths":1351,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":808227,"Deaths":11268,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":162844,"Deaths":3900,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":71416,"Deaths":2077,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":100887,"Deaths":996,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":515201,"Deaths":7820,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":97189,"Deaths":1012,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":46785,"Deaths":610,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":240384,"Deaths":6483,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":301502,"Deaths":7343,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":929712,"Deaths":15953,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":7585,"Deaths":128,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":103217,"Deaths":1989,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":187512,"Deaths":2649,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":39663,"Deaths":823,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":898565,"Deaths":16207,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":11065,"Deaths":112,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":142452,"Deaths":1752,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":83350,"Deaths":1252,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":263592,"Deaths":4994,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":13519,"Deaths":131,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":28861,"Deaths":358,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":37562,"Deaths":564,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4576,"Deaths":54,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":43387,"Deaths":329,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":13246,"Deaths":128,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":45818,"Deaths":562,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":25721,"Deaths":251,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":23712,"Deaths":326,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":28143,"Deaths":292,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":34477,"Deaths":353,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":45002,"Deaths":659,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":166318,"Deaths":1793,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":27704,"Deaths":481,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":279813,"Deaths":4487,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":42977,"Deaths":545,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":21646,"Deaths":223,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":26284,"Deaths":199,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":27769,"Deaths":483,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":30754,"Deaths":365,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":204223,"Deaths":2442,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":101503,"Deaths":1616,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":74230,"Deaths":1679,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":106829,"Deaths":2448,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":97496,"Deaths":3010,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":188830,"Deaths":5910,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":127961,"Deaths":3395,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":104399,"Deaths":2441,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":207642,"Deaths":4722,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":66340,"Deaths":1813,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":116873,"Deaths":2375,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":259797,"Deaths":6208,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":151382,"Deaths":3299,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":24940,"Deaths":983,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":48462,"Deaths":1559,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":183184,"Deaths":4546,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":86599,"Deaths":2364,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":194121,"Deaths":4081,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":99556,"Deaths":2307,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":102057,"Deaths":1597,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":39391,"Deaths":1365,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":107499,"Deaths":1885,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":90919,"Deaths":1622,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":85356,"Deaths":2079,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":78189,"Deaths":1521,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":69244,"Deaths":1762,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":143105,"Deaths":3377,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":117221,"Deaths":2438,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":944,"Deaths":1,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":5657,"Deaths":104,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2725,"Deaths":37,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":1650,"Deaths":2,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":13323,"Deaths":103,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":7732441,"Deaths":122627,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":69,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":5997,"Deaths":98,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":9738,"Deaths":57,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":41,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":276220,"Deaths":2715,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":645697,"Deaths":9163,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":2982,"Deaths":23,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":442953,"Deaths":6167,"Recovered":"" }
		]}
