ReportDate[612] =	{"Date":"2021-11-26",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":2110,"Deaths":14,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":81170,"Deaths":625,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":283,"Deaths":0,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":2117,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":931,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":239,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":118777,"Deaths":1318,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1122,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":241982,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":206415,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":203151,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":142956,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":211073,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":195489,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":107552,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":45931,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":83817,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":29221,"Deaths":26840,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":64388,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":169658,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":88200,"Deaths":1846,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":241394,"Deaths":6344,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":124500,"Deaths":2002,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":429611,"Deaths":13800,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1258356,"Deaths":27277,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":949458,"Deaths":24624,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":517608,"Deaths":11026,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":618540,"Deaths":13144,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":933798,"Deaths":24495,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":364555,"Deaths":10277,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":548939,"Deaths":13744,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":378445,"Deaths":9677,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2205611,"Deaths":56129,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":607108,"Deaths":16879,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":460032,"Deaths":9516,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1577158,"Deaths":40766,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":639000,"Deaths":20217,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":330963,"Deaths":7178,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":380839,"Deaths":7484,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1488680,"Deaths":36054,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1341850,"Deaths":68998,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":276625,"Deaths":6628,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":128289,"Deaths":2050,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1231250,"Deaths":19966,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4436451,"Deaths":153879,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":278179,"Deaths":6042,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":232191,"Deaths":3915,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":334203,"Deaths":3235,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":217099,"Deaths":2322,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":67420,"Deaths":1305,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":8087,"Deaths":123,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":2048,"Deaths":18,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":2059,"Deaths":12,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":8169,"Deaths":108,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":674,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":623597,"Deaths":10043,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":363,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":444584,"Deaths":11571,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":80775,"Deaths":916,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":1475,"Deaths":13,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":65137,"Deaths":1266,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":101212,"Deaths":1528,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":28504,"Deaths":542,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":29335,"Deaths":368,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":9570,"Deaths":80,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":159859,"Deaths":2726,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":52477,"Deaths":1055,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":93586,"Deaths":1430,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":51571,"Deaths":703,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29614,"Deaths":499,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":107299,"Deaths":1814,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":739540,"Deaths":19623,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":37919,"Deaths":658,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":71995,"Deaths":1599,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":43951,"Deaths":815,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":46,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":132828,"Deaths":3539,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1008,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1191,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":610,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1320,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":344,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3294,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":393,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":159,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1453,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":1992,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1637,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12421,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68311,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1199,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":618,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1619,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":959,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":583,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":783,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":122,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":30,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":707,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":1015,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2842,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":264,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1269,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":530,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":981,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1683,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1501,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6898,"Deaths":257,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":767788,"Deaths":16516,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":13985,"Deaths":471,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":338283,"Deaths":9660,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":160252,"Deaths":3021,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":106285,"Deaths":2575,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":101211,"Deaths":2282,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1461660,"Deaths":27607,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":22988,"Deaths":941,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":35891,"Deaths":934,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":56762,"Deaths":1586,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":91544,"Deaths":2522,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16495,"Deaths":400,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":104538,"Deaths":3741,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":266094,"Deaths":6844,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2475,"Deaths":30,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5156,"Deaths":97,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":88888,"Deaths":3157,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":45563,"Deaths":1398,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":99555,"Deaths":3429,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":90099,"Deaths":2282,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":90342,"Deaths":3040,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":98078,"Deaths":4492,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":16962,"Deaths":681,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":57893,"Deaths":1792,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":88412,"Deaths":2245,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":8020,"Deaths":146,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":230072,"Deaths":7376,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":59632,"Deaths":1627,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":108073,"Deaths":3677,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":415870,"Deaths":13151,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1794,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":2999,"Deaths":53,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":3408,"Deaths":13,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":1332,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":45802,"Deaths":325,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":45609,"Deaths":636,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":55080,"Deaths":823,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":45010,"Deaths":707,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":20938,"Deaths":185,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":12067,"Deaths":276,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":59048,"Deaths":381,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1666,"Deaths":6,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":61,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":4013,"Deaths":56,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":807472,"Deaths":11677,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":1102641,"Deaths":17376,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":270426,"Deaths":3818,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":171184,"Deaths":4088,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":39176,"Deaths":547,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":112307,"Deaths":1885,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":407506,"Deaths":8118,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":68652,"Deaths":1320,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":370281,"Deaths":6324,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":1155326,"Deaths":18884,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":228227,"Deaths":4257,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":59871,"Deaths":1111,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":474479,"Deaths":10883,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":150767,"Deaths":3781,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":95103,"Deaths":1787,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":203944,"Deaths":4927,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":18475,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7678,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2072198,"Deaths":14432,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":55260,"Deaths":280,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":616312,"Deaths":6086,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":726209,"Deaths":9663,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":65438,"Deaths":820,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1006706,"Deaths":13593,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10683,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1440807,"Deaths":25095,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":178799,"Deaths":3381,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":827354,"Deaths":10092,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":771643,"Deaths":10054,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":226859,"Deaths":3842,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":336237,"Deaths":4470,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":349196,"Deaths":5140,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":2994963,"Deaths":38193,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":5124618,"Deaths":39125,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":21467,"Deaths":213,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10394,"Deaths":51,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":793097,"Deaths":10528,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6633105,"Deaths":140891,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":125098,"Deaths":1968,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":84394,"Deaths":1468,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":133921,"Deaths":488,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":32096,"Deaths":696,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1048228,"Deaths":8403,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":128825,"Deaths":1872,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":603173,"Deaths":16593,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":954715,"Deaths":8955,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":32207,"Deaths":403,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2723991,"Deaths":36443,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":675319,"Deaths":3987,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":84771,"Deaths":820,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1710368,"Deaths":22909,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":344169,"Deaths":7407,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1613451,"Deaths":19439,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":87106,"Deaths":2586,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":31455,"Deaths":625,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":91990,"Deaths":1491,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":486652,"Deaths":8204,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":451021,"Deaths":13750,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":129143,"Deaths":3955,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":418738,"Deaths":8959,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":121101,"Deaths":4458,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":925051,"Deaths":34330,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":122457,"Deaths":3143,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":15146,"Deaths":503,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":86441,"Deaths":1236,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":51550,"Deaths":1384,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":396435,"Deaths":11879,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":278464,"Deaths":6881,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":78444,"Deaths":1690,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":321696,"Deaths":7179,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":299575,"Deaths":7388,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":67237,"Deaths":1482,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":12984,"Deaths":479,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":509336,"Deaths":11935,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":106861,"Deaths":1161,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1925,"Deaths":27,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":5897,"Deaths":38,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":100445,"Deaths":1028,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":5412,"Deaths":82,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":3115,"Deaths":38,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":74597,"Deaths":624,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":9487,"Deaths":176,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":18907,"Deaths":218,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":16854,"Deaths":176,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":22159,"Deaths":202,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":61116,"Deaths":1472,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":78674,"Deaths":1396,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":24448,"Deaths":220,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":7969,"Deaths":129,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3487,"Deaths":53,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":4702,"Deaths":38,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":9103,"Deaths":66,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":169234,"Deaths":1313,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4167,"Deaths":33,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":14395,"Deaths":136,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":35986,"Deaths":291,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":14811,"Deaths":163,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":16280,"Deaths":118,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":6137,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":8883,"Deaths":97,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":6119,"Deaths":73,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":15641,"Deaths":149,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":8019,"Deaths":61,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":8187,"Deaths":84,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":15532,"Deaths":136,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":50307,"Deaths":398,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":203081,"Deaths":3064,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4463,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":5866,"Deaths":30,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":115807,"Deaths":1056,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":12432,"Deaths":104,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":1732,"Deaths":5,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":26786,"Deaths":209,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":15479,"Deaths":117,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3291,"Deaths":66,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":382163,"Deaths":3164,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1669,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":4867,"Deaths":52,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":5300,"Deaths":62,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":3555,"Deaths":56,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":5788,"Deaths":93,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":5156,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":230315,"Deaths":3757,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":158375,"Deaths":2079,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":154612,"Deaths":1147,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":70425,"Deaths":933,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":107986,"Deaths":1266,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":85397,"Deaths":703,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":122134,"Deaths":1235,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":6202,"Deaths":123,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":152111,"Deaths":1645,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":231644,"Deaths":2672,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":250229,"Deaths":1577,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":748824,"Deaths":9758,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":75704,"Deaths":575,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":201760,"Deaths":2600,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":10443,"Deaths":149,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":8319,"Deaths":21,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":36985,"Deaths":2927,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":79555,"Deaths":10299,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":56863,"Deaths":2388,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":24156,"Deaths":2082,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":23500,"Deaths":2281,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":72551,"Deaths":8272,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":983222,"Deaths":40098,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":97378,"Deaths":7561,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":33303,"Deaths":2034,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":49668,"Deaths":3090,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":195718,"Deaths":12968,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":76976,"Deaths":6229,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":62648,"Deaths":7852,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":163106,"Deaths":17548,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":378627,"Deaths":44328,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":73558,"Deaths":8198,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":50272,"Deaths":4841,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":34176,"Deaths":2865,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":206736,"Deaths":13390,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":83052,"Deaths":5582,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":125695,"Deaths":15490,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":98945,"Deaths":5597,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":59792,"Deaths":4072,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":105074,"Deaths":6689,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":74443,"Deaths":8827,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":117046,"Deaths":8690,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":143571,"Deaths":5602,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":102943,"Deaths":6942,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":29423,"Deaths":2983,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":123789,"Deaths":14811,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":75049,"Deaths":5670,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":42016,"Deaths":3408,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":16291,"Deaths":174,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":2858,"Deaths":22,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":17384,"Deaths":178,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":50631,"Deaths":386,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":58231,"Deaths":276,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":75012,"Deaths":515,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":293108,"Deaths":2298,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":61980,"Deaths":288,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":184219,"Deaths":1861,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":391853,"Deaths":3302,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":423389,"Deaths":2849,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":167015,"Deaths":1245,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":4573,"Deaths":75,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":10193,"Deaths":15,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":199382,"Deaths":1347,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":48945,"Deaths":272,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":591457,"Deaths":4563,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":34542,"Deaths":742,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":33471,"Deaths":359,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10411,"Deaths":186,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":107601,"Deaths":952,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":179888,"Deaths":5830,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":442876,"Deaths":13015,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":475097,"Deaths":7620,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":32127,"Deaths":1265,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":78840,"Deaths":6711,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":26526,"Deaths":1517,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":116162,"Deaths":9697,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":34554,"Deaths":2134,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":66430,"Deaths":4139,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":102287,"Deaths":10030,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":74874,"Deaths":4796,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":16365,"Deaths":1166,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":35980,"Deaths":2700,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":60055,"Deaths":8546,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":87680,"Deaths":7052,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":90651,"Deaths":10276,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":62815,"Deaths":8621,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":974442,"Deaths":88803,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":45224,"Deaths":4264,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":13975,"Deaths":772,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":29827,"Deaths":1521,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":16015,"Deaths":1049,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":91118,"Deaths":12084,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":41300,"Deaths":4208,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":48999,"Deaths":3030,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":30593,"Deaths":1960,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":19195,"Deaths":1579,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":32178,"Deaths":3041,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":2963,"Deaths":65,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":23823,"Deaths":657,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":101953,"Deaths":5642,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":24194,"Deaths":454,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":45476,"Deaths":519,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":112067,"Deaths":1343,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":72988,"Deaths":2168,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":103697,"Deaths":3418,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":71472,"Deaths":1493,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":88470,"Deaths":2219,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":68617,"Deaths":2150,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":28202,"Deaths":815,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":124205,"Deaths":5018,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":2817,"Deaths":25,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":42344,"Deaths":3229,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":60572,"Deaths":2921,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":25819,"Deaths":416,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":136330,"Deaths":6095,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":61217,"Deaths":2094,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":10410,"Deaths":333,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":38483,"Deaths":1153,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":74618,"Deaths":999,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":33323,"Deaths":690,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":58339,"Deaths":1015,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":22218,"Deaths":482,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":29763,"Deaths":848,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":82206,"Deaths":1065,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":72512,"Deaths":1561,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":107758,"Deaths":1027,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":49094,"Deaths":1586,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":88752,"Deaths":1660,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":70589,"Deaths":669,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":88747,"Deaths":2262,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":43884,"Deaths":973,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":96000,"Deaths":8732,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":149800,"Deaths":7357,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":44257,"Deaths":860,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":75224,"Deaths":1767,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":88943,"Deaths":2757,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":73051,"Deaths":2379,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":12645,"Deaths":310,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":25803,"Deaths":746,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":36015,"Deaths":866,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1933979,"Deaths":33821,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":581202,"Deaths":10227,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":85656,"Deaths":2528,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":3173,"Deaths":72,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":211482,"Deaths":8732,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":28152,"Deaths":740,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":58416,"Deaths":587,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":81151,"Deaths":3736,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":112229,"Deaths":2772,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":62078,"Deaths":1268,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":99591,"Deaths":3105,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":90318,"Deaths":4137,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":137998,"Deaths":6746,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":86184,"Deaths":1384,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":65101,"Deaths":1055,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":172931,"Deaths":8579,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":54552,"Deaths":1891,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":779037,"Deaths":25931,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":69450,"Deaths":1674,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":37371,"Deaths":431,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":175951,"Deaths":5365,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":117867,"Deaths":4521,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":76651,"Deaths":2108,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":110888,"Deaths":5070,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":176415,"Deaths":8294,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":53821,"Deaths":1380,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":37057,"Deaths":1215,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":54837,"Deaths":625,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":66968,"Deaths":3851,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":86892,"Deaths":2073,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":79613,"Deaths":2793,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":30368,"Deaths":294,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":73632,"Deaths":3024,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":109293,"Deaths":3322,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":71194,"Deaths":2459,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":116016,"Deaths":4430,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":88573,"Deaths":2522,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":174248,"Deaths":5627,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":57920,"Deaths":848,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":76292,"Deaths":1533,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":86331,"Deaths":1591,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":820184,"Deaths":11335,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":168277,"Deaths":3937,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":73139,"Deaths":2088,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":104803,"Deaths":1021,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":528723,"Deaths":7888,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":102321,"Deaths":1045,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":47841,"Deaths":613,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":244128,"Deaths":6525,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":308144,"Deaths":7407,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":956245,"Deaths":16013,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":7658,"Deaths":128,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":104409,"Deaths":1995,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":192089,"Deaths":2663,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":40532,"Deaths":828,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":912010,"Deaths":16289,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":11227,"Deaths":113,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":146160,"Deaths":1765,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":87702,"Deaths":1262,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":275420,"Deaths":5040,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":13915,"Deaths":131,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":29274,"Deaths":359,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":38454,"Deaths":565,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4710,"Deaths":54,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":44336,"Deaths":328,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":13404,"Deaths":128,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":46318,"Deaths":566,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":26642,"Deaths":252,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":23977,"Deaths":327,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":28709,"Deaths":295,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":35709,"Deaths":354,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":45541,"Deaths":661,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":170372,"Deaths":1812,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":28285,"Deaths":484,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":286957,"Deaths":4528,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":44001,"Deaths":550,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":22337,"Deaths":227,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":26976,"Deaths":203,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":28214,"Deaths":487,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":32626,"Deaths":374,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":208091,"Deaths":2460,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":116398,"Deaths":2146,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":87956,"Deaths":2090,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":115167,"Deaths":2781,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":117462,"Deaths":3511,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":229759,"Deaths":7626,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":151691,"Deaths":4460,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":120023,"Deaths":2835,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":233427,"Deaths":5533,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":75778,"Deaths":2448,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":136280,"Deaths":2896,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":294563,"Deaths":7372,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":171423,"Deaths":4090,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":28857,"Deaths":1198,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":56592,"Deaths":1955,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":207286,"Deaths":5383,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":106151,"Deaths":2964,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":226528,"Deaths":5122,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":123675,"Deaths":3105,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":119141,"Deaths":2012,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":47842,"Deaths":1647,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":123873,"Deaths":2505,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":101364,"Deaths":1915,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":102014,"Deaths":2608,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":92173,"Deaths":1914,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":78874,"Deaths":2004,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":169130,"Deaths":4242,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":132217,"Deaths":2945,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":1334,"Deaths":3,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":5730,"Deaths":106,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2773,"Deaths":38,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":6599,"Deaths":4,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":17326,"Deaths":103,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":8538517,"Deaths":125801,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":79,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":7129,"Deaths":98,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":10993,"Deaths":66,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":44,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":313011,"Deaths":2865,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":718285,"Deaths":9545,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":3093,"Deaths":24,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":501028,"Deaths":6382,"Recovered":"" }
		]}
