ReportDate[631] =	{"Date":"2021-12-15",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":2222,"Deaths":15,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":90333,"Deaths":641,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":343,"Deaths":1,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":2210,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":1081,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":241,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":141415,"Deaths":1436,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1125,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":286677,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":229887,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":246172,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":171044,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":238831,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":215941,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":131216,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":52950,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":95264,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":31976,"Deaths":27729,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":74973,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":205189,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":88300,"Deaths":1850,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":241846,"Deaths":6372,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":125803,"Deaths":2008,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":432003,"Deaths":13817,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1264804,"Deaths":27417,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":953335,"Deaths":24738,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":518502,"Deaths":11074,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":625915,"Deaths":13255,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":943102,"Deaths":24604,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":368218,"Deaths":10343,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":551675,"Deaths":13769,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":379502,"Deaths":9704,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2215822,"Deaths":56492,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":617636,"Deaths":17000,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":462620,"Deaths":9565,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1590938,"Deaths":40848,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":643365,"Deaths":20344,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":333766,"Deaths":7236,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":384672,"Deaths":7530,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1499084,"Deaths":36320,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1349564,"Deaths":69303,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":281603,"Deaths":6688,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":128763,"Deaths":2064,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1238056,"Deaths":20101,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4449806,"Deaths":154848,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":278408,"Deaths":6054,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":234113,"Deaths":3927,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":339997,"Deaths":3286,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":224245,"Deaths":2393,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":70340,"Deaths":1357,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":9973,"Deaths":144,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":2106,"Deaths":18,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":2076,"Deaths":12,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":8968,"Deaths":110,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":676,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":646075,"Deaths":10145,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":420,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":471741,"Deaths":11622,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":81961,"Deaths":941,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":1606,"Deaths":14,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":66150,"Deaths":1278,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":102846,"Deaths":1542,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":28723,"Deaths":543,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":30317,"Deaths":376,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":10127,"Deaths":89,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":164777,"Deaths":2783,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":54133,"Deaths":1074,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":97460,"Deaths":1461,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":52792,"Deaths":711,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29871,"Deaths":502,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":108894,"Deaths":1843,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":747712,"Deaths":19826,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":38956,"Deaths":670,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":72774,"Deaths":1617,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":44488,"Deaths":821,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":46,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":136118,"Deaths":3591,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1009,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1198,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":610,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1336,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":344,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3353,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":499,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":159,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1458,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":2035,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1638,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12496,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68316,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1200,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":1173,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1621,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":959,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":587,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":788,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":122,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":30,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":731,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":1036,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2929,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":265,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1298,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":537,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":981,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1774,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1823,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6977,"Deaths":258,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":777131,"Deaths":16734,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":14327,"Deaths":479,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":341159,"Deaths":9724,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":161251,"Deaths":3047,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":106657,"Deaths":2578,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":101464,"Deaths":2290,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1467458,"Deaths":27671,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":23053,"Deaths":943,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":36057,"Deaths":936,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":57276,"Deaths":1592,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":92653,"Deaths":2548,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16551,"Deaths":403,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":104694,"Deaths":3741,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":266832,"Deaths":6851,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2569,"Deaths":33,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5168,"Deaths":97,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":89380,"Deaths":3171,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":46742,"Deaths":1428,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":100892,"Deaths":3464,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":90531,"Deaths":2289,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":90716,"Deaths":3047,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":100848,"Deaths":4622,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":17575,"Deaths":701,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":58602,"Deaths":1820,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":88935,"Deaths":2260,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":8326,"Deaths":149,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":233392,"Deaths":7455,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":59724,"Deaths":1627,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":108322,"Deaths":3687,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":419644,"Deaths":13244,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1796,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":3044,"Deaths":54,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":4477,"Deaths":13,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":1917,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":46510,"Deaths":333,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":46335,"Deaths":636,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":55375,"Deaths":828,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":46597,"Deaths":740,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":21139,"Deaths":185,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":12525,"Deaths":280,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":67237,"Deaths":393,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1683,"Deaths":6,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":96,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":4059,"Deaths":56,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":952669,"Deaths":12447,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":1263982,"Deaths":18851,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":304384,"Deaths":3938,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":217353,"Deaths":4408,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":43234,"Deaths":575,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":125148,"Deaths":1940,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":452337,"Deaths":8374,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":88959,"Deaths":1404,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":414704,"Deaths":6633,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":1297131,"Deaths":19690,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":262391,"Deaths":4452,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":69625,"Deaths":1178,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":606796,"Deaths":11971,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":202583,"Deaths":4027,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":107395,"Deaths":1850,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":261777,"Deaths":5469,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":20100,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7698,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2075271,"Deaths":14471,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":55319,"Deaths":280,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":618988,"Deaths":6137,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":726346,"Deaths":12092,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":65659,"Deaths":1076,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1007295,"Deaths":13595,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10686,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1441850,"Deaths":25100,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":179565,"Deaths":3482,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":828299,"Deaths":10100,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":772086,"Deaths":10060,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":228116,"Deaths":3864,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":339271,"Deaths":4503,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":349466,"Deaths":5142,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":3001251,"Deaths":38277,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":5204422,"Deaths":43626,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":21865,"Deaths":216,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10406,"Deaths":51,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":793415,"Deaths":10529,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6646061,"Deaths":141298,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":125569,"Deaths":1993,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":84715,"Deaths":1477,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":139024,"Deaths":529,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":32161,"Deaths":700,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1052145,"Deaths":8439,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":129261,"Deaths":1878,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":603814,"Deaths":16623,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":955147,"Deaths":8959,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":32443,"Deaths":406,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2737335,"Deaths":36644,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":678874,"Deaths":4010,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":84945,"Deaths":827,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1710606,"Deaths":22915,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":344513,"Deaths":7413,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1624715,"Deaths":19633,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":91526,"Deaths":2610,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":32532,"Deaths":627,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":98139,"Deaths":1533,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":509210,"Deaths":8311,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":480144,"Deaths":13953,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":140676,"Deaths":4099,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":448162,"Deaths":9102,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":130510,"Deaths":4503,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":975451,"Deaths":34648,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":130596,"Deaths":3176,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":15418,"Deaths":507,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":94898,"Deaths":1278,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":55125,"Deaths":1401,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":418655,"Deaths":11929,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":284723,"Deaths":6930,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":81310,"Deaths":1711,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":337049,"Deaths":7307,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":312243,"Deaths":7468,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":69819,"Deaths":1497,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":14008,"Deaths":485,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":561882,"Deaths":12103,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":106983,"Deaths":1161,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1934,"Deaths":27,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":5900,"Deaths":38,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":100551,"Deaths":1028,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":5412,"Deaths":82,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":3115,"Deaths":38,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":74678,"Deaths":625,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":9495,"Deaths":176,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":18931,"Deaths":218,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":17080,"Deaths":176,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":22175,"Deaths":202,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":61210,"Deaths":1474,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":78757,"Deaths":1398,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":24466,"Deaths":220,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":7970,"Deaths":129,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3487,"Deaths":53,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":4702,"Deaths":38,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":9103,"Deaths":66,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":169444,"Deaths":1315,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4167,"Deaths":33,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":14395,"Deaths":136,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":36016,"Deaths":292,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":14816,"Deaths":163,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":16286,"Deaths":118,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":6139,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":8895,"Deaths":97,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":6119,"Deaths":73,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":15649,"Deaths":149,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":8125,"Deaths":61,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":8187,"Deaths":84,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":15551,"Deaths":136,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":50364,"Deaths":398,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":203317,"Deaths":3064,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4463,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":5866,"Deaths":30,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":115948,"Deaths":1059,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":12441,"Deaths":104,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":1733,"Deaths":5,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":26864,"Deaths":209,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":15505,"Deaths":117,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3291,"Deaths":66,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":382442,"Deaths":3172,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1669,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":4868,"Deaths":52,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":5303,"Deaths":62,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":3604,"Deaths":56,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":5794,"Deaths":93,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":5159,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":238712,"Deaths":3815,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":164648,"Deaths":2125,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":163389,"Deaths":1214,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":74058,"Deaths":947,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":111458,"Deaths":1298,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":91672,"Deaths":737,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":126261,"Deaths":1316,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":6849,"Deaths":131,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":157544,"Deaths":1694,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":237759,"Deaths":2750,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":251857,"Deaths":1613,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":772314,"Deaths":9872,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":79512,"Deaths":662,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":207395,"Deaths":2643,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":10719,"Deaths":151,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":8993,"Deaths":21,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":38046,"Deaths":2991,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":86618,"Deaths":10685,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":57589,"Deaths":2405,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":24237,"Deaths":2104,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":23577,"Deaths":2294,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":76652,"Deaths":8495,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":990026,"Deaths":40252,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":99854,"Deaths":7702,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":33395,"Deaths":2040,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":50375,"Deaths":3132,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":199804,"Deaths":13229,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":77281,"Deaths":6311,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":62906,"Deaths":7891,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":164611,"Deaths":17711,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":380842,"Deaths":44558,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":73777,"Deaths":8248,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":50742,"Deaths":4941,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":34398,"Deaths":2908,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":208171,"Deaths":13665,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":83783,"Deaths":5634,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":126103,"Deaths":15665,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":99617,"Deaths":5648,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":59984,"Deaths":4087,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":106507,"Deaths":6755,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":75087,"Deaths":8944,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":120994,"Deaths":8960,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":144018,"Deaths":5709,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":103803,"Deaths":7075,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":29578,"Deaths":2995,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":124395,"Deaths":15021,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":75451,"Deaths":5707,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":42417,"Deaths":3426,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":16673,"Deaths":178,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":3162,"Deaths":22,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":17657,"Deaths":183,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":58543,"Deaths":406,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":67025,"Deaths":296,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":89513,"Deaths":550,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":334787,"Deaths":2477,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":69954,"Deaths":317,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":217116,"Deaths":1990,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":449379,"Deaths":3469,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":478114,"Deaths":2995,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":189370,"Deaths":1297,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":4662,"Deaths":75,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":13213,"Deaths":18,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":228921,"Deaths":1412,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":59358,"Deaths":290,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":665145,"Deaths":4738,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":2,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":34627,"Deaths":744,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":33540,"Deaths":363,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10428,"Deaths":186,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":108198,"Deaths":963,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":180825,"Deaths":5900,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":444032,"Deaths":13053,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":478564,"Deaths":7640,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":32356,"Deaths":1275,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":80082,"Deaths":6735,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":26633,"Deaths":1520,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":116696,"Deaths":9726,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":34854,"Deaths":2148,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":66849,"Deaths":4151,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":103052,"Deaths":10067,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":75274,"Deaths":4817,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":16426,"Deaths":1178,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":36324,"Deaths":2705,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":60589,"Deaths":8571,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":88394,"Deaths":7070,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":92114,"Deaths":10335,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":63676,"Deaths":8647,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":987590,"Deaths":89096,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":45267,"Deaths":4270,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":14020,"Deaths":773,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":29928,"Deaths":1529,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":16185,"Deaths":1050,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":93063,"Deaths":12181,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":41646,"Deaths":4232,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":49144,"Deaths":3038,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":31004,"Deaths":1972,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":19437,"Deaths":1587,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":32243,"Deaths":3060,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":3950,"Deaths":169,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":25811,"Deaths":695,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":111811,"Deaths":6158,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":24838,"Deaths":488,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":50446,"Deaths":574,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":118918,"Deaths":1455,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":77646,"Deaths":2274,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":115318,"Deaths":4044,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":77727,"Deaths":1647,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":93066,"Deaths":2604,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":73022,"Deaths":2298,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":29800,"Deaths":876,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":136324,"Deaths":5583,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":2923,"Deaths":31,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":45080,"Deaths":3586,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":63697,"Deaths":3079,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":27399,"Deaths":448,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":147728,"Deaths":6581,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":65063,"Deaths":2312,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":11115,"Deaths":373,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":40454,"Deaths":1321,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":79203,"Deaths":1151,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":33739,"Deaths":713,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":62217,"Deaths":1124,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":23152,"Deaths":501,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":31184,"Deaths":896,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":86859,"Deaths":1135,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":79445,"Deaths":1636,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":117772,"Deaths":1148,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":52002,"Deaths":1783,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":92919,"Deaths":1861,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":75388,"Deaths":716,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":94033,"Deaths":2462,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":47223,"Deaths":1044,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":109853,"Deaths":9408,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":163513,"Deaths":8024,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":47930,"Deaths":948,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":79635,"Deaths":1915,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":96024,"Deaths":2941,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":79948,"Deaths":2611,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":13283,"Deaths":329,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":28114,"Deaths":888,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":38838,"Deaths":962,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1991707,"Deaths":35558,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":618194,"Deaths":11265,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":89240,"Deaths":2659,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":3390,"Deaths":84,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":223803,"Deaths":9387,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":29749,"Deaths":857,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":62730,"Deaths":714,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":88618,"Deaths":4016,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":123164,"Deaths":3005,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":67270,"Deaths":1390,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":105098,"Deaths":3311,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":97112,"Deaths":4457,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":151038,"Deaths":7169,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":94910,"Deaths":1471,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":68711,"Deaths":1168,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":185309,"Deaths":9211,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":58780,"Deaths":2262,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":821320,"Deaths":27067,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":74058,"Deaths":1736,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":39904,"Deaths":481,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":191664,"Deaths":5961,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":127846,"Deaths":4871,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":81655,"Deaths":2251,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":119676,"Deaths":5679,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":189356,"Deaths":8924,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":57827,"Deaths":1567,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":41134,"Deaths":1353,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":59205,"Deaths":652,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":71549,"Deaths":4065,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":93815,"Deaths":2220,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":85475,"Deaths":3166,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":31308,"Deaths":317,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":77650,"Deaths":3162,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":116217,"Deaths":3578,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":76991,"Deaths":2869,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":124033,"Deaths":5118,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":95523,"Deaths":2771,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":187426,"Deaths":6390,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":60353,"Deaths":914,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":81507,"Deaths":1698,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":92375,"Deaths":1718,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":843607,"Deaths":11385,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":180654,"Deaths":4007,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":80180,"Deaths":2117,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":112739,"Deaths":1035,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":560115,"Deaths":7987,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":111022,"Deaths":1079,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":50596,"Deaths":620,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":249919,"Deaths":6554,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":325504,"Deaths":7479,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":1008775,"Deaths":16066,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":8168,"Deaths":130,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":107709,"Deaths":2006,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":206824,"Deaths":2704,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":42584,"Deaths":831,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":938588,"Deaths":16335,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":11818,"Deaths":116,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":154398,"Deaths":1777,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":98081,"Deaths":1272,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":301987,"Deaths":5119,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":14618,"Deaths":133,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":30488,"Deaths":360,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":39936,"Deaths":567,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4817,"Deaths":54,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":45940,"Deaths":333,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":13774,"Deaths":129,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":47560,"Deaths":568,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":27734,"Deaths":256,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":24376,"Deaths":329,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":29139,"Deaths":298,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":37508,"Deaths":358,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":46506,"Deaths":661,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":177904,"Deaths":1821,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":29276,"Deaths":486,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":298828,"Deaths":4542,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":46005,"Deaths":554,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":23402,"Deaths":229,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":27645,"Deaths":203,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":29408,"Deaths":488,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":34897,"Deaths":378,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":212972,"Deaths":2474,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":125121,"Deaths":2431,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":92406,"Deaths":2276,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":117722,"Deaths":2926,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":124577,"Deaths":3966,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":239018,"Deaths":8495,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":162446,"Deaths":4936,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":124721,"Deaths":3002,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":240025,"Deaths":6081,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":77920,"Deaths":2620,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":143107,"Deaths":3169,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":316018,"Deaths":7925,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":180842,"Deaths":4468,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":31779,"Deaths":1373,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":58877,"Deaths":2107,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":215646,"Deaths":5782,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":112883,"Deaths":3171,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":235779,"Deaths":5419,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":134666,"Deaths":3499,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":125041,"Deaths":2178,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":51433,"Deaths":1790,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":128731,"Deaths":2727,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":105174,"Deaths":2033,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":109381,"Deaths":2929,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":100339,"Deaths":2107,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":84793,"Deaths":2197,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":178081,"Deaths":4959,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":138041,"Deaths":3148,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":1592,"Deaths":4,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":5784,"Deaths":106,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2842,"Deaths":39,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":8007,"Deaths":9,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":21221,"Deaths":107,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":9343520,"Deaths":127608,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":83,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":7629,"Deaths":100,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":12812,"Deaths":67,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":44,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":345196,"Deaths":2936,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":777885,"Deaths":9746,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":3151,"Deaths":25,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":543685,"Deaths":6501,"Recovered":"" }
		]}
