ReportDate[37] =	{"Date":"2020-04-28",
		"Data":[
		{"Prov":"Alberta","Region":"Canada","Cases":4850,"Deaths":80,"Recovered":0 },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":3,"Deaths":0,"Recovered":3 },
		{"Prov":"Anhui","Region":"China","Cases":991,"Deaths":6,"Recovered":985 },
		{"Prov":"Aruba","Region":"Netherlands","Cases":100,"Deaths":2,"Recovered":73 },
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":106,"Deaths":3,"Recovered":101 },
		{"Prov":"Beijing","Region":"China","Cases":593,"Deaths":9,"Recovered":538 },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":110,"Deaths":6,"Recovered":44 },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":5,"Deaths":0,"Recovered":0 },
		{"Prov":"British Columbia","Region":"Canada","Cases":2053,"Deaths":106,"Recovered":0 },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":6,"Deaths":1,"Recovered":3 },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":70,"Deaths":1,"Recovered":10 },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":530,"Deaths":36,"Recovered":352 },
		{"Prov":"Chongqing","Region":"China","Cases":579,"Deaths":6,"Recovered":573 },
		{"Prov":"Curacao","Region":"Netherlands","Cases":16,"Deaths":1,"Recovered":11 },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":0 },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":13,"Deaths":0,"Recovered":11 },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":187,"Deaths":0,"Recovered":181 },
		{"Prov":"French Guiana","Region":"France","Cases":125,"Deaths":1,"Recovered":93 },
		{"Prov":"French Polynesia","Region":"France","Cases":58,"Deaths":0,"Recovered":49 },
		{"Prov":"Fujian","Region":"China","Cases":355,"Deaths":1,"Recovered":352 },
		{"Prov":"Gansu","Region":"China","Cases":139,"Deaths":2,"Recovered":137 },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":141,"Deaths":0,"Recovered":131 },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":0 },
		{"Prov":"Greenland","Region":"Denmark","Cases":11,"Deaths":0,"Recovered":11 },
		{"Prov":"Guadeloupe","Region":"France","Cases":149,"Deaths":12,"Recovered":82 },
		{"Prov":"Guangdong","Region":"China","Cases":1588,"Deaths":8,"Recovered":1554 },
		{"Prov":"Guangxi","Region":"China","Cases":254,"Deaths":2,"Recovered":252 },
		{"Prov":"Guizhou","Region":"China","Cases":147,"Deaths":2,"Recovered":145 },
		{"Prov":"Hainan","Region":"China","Cases":168,"Deaths":6,"Recovered":162 },
		{"Prov":"Hebei","Region":"China","Cases":328,"Deaths":6,"Recovered":318 },
		{"Prov":"Heilongjiang","Region":"China","Cases":939,"Deaths":13,"Recovered":587 },
		{"Prov":"Henan","Region":"China","Cases":1276,"Deaths":22,"Recovered":1254 },
		{"Prov":"Hong Kong","Region":"China","Cases":1037,"Deaths":4,"Recovered":811 },
		{"Prov":"Hubei","Region":"China","Cases":68128,"Deaths":4512,"Recovered":63616 },
		{"Prov":"Hunan","Region":"China","Cases":1019,"Deaths":4,"Recovered":1015 },
		{"Prov":"Inner Mongolia","Region":"China","Cases":199,"Deaths":1,"Recovered":146 },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":309,"Deaths":21,"Recovered":252 },
		{"Prov":"Jiangsu","Region":"China","Cases":653,"Deaths":0,"Recovered":647 },
		{"Prov":"Jiangxi","Region":"China","Cases":937,"Deaths":1,"Recovered":936 },
		{"Prov":"Jilin","Region":"China","Cases":110,"Deaths":1,"Recovered":99 },
		{"Prov":"Liaoning","Region":"China","Cases":146,"Deaths":2,"Recovered":143 },
		{"Prov":"Macau","Region":"China","Cases":45,"Deaths":0,"Recovered":33 },
		{"Prov":"Manitoba","Region":"Canada","Cases":273,"Deaths":6,"Recovered":0 },
		{"Prov":"Martinique","Region":"France","Cases":175,"Deaths":14,"Recovered":83 },
		{"Prov":"Mayotte","Region":"France","Cases":460,"Deaths":4,"Recovered":235 },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":11,"Deaths":1,"Recovered":2 },
		{"Prov":"New Brunswick","Region":"Canada","Cases":118,"Deaths":0,"Recovered":0 },
		{"Prov":"New Caledonia","Region":"France","Cases":18,"Deaths":0,"Recovered":17 },
		{"Prov":"New South Wales","Region":"Australia","Cases":3016,"Deaths":39,"Recovered":2266 },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":258,"Deaths":3,"Recovered":0 },
		{"Prov":"Ningxia","Region":"China","Cases":75,"Deaths":0,"Recovered":75 },
		{"Prov":"Northern Territory","Region":"Australia","Cases":28,"Deaths":0,"Recovered":25 },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":5,"Deaths":0,"Recovered":0 },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":915,"Deaths":27,"Recovered":0 },
		{"Prov":"Ontario","Region":"Canada","Cases":16500,"Deaths":1072,"Recovered":0 },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":27,"Deaths":0,"Recovered":0 },
		{"Prov":"Qinghai","Region":"China","Cases":18,"Deaths":0,"Recovered":18 },
		{"Prov":"Quebec","Region":"Canada","Cases":25761,"Deaths":1683,"Recovered":0 },
		{"Prov":"Queensland","Region":"Australia","Cases":1034,"Deaths":6,"Recovered":934 },
		{"Prov":"Recovered","Region":"Canada","Cases":0,"Deaths":0,"Recovered":19231 },
		{"Prov":"Reunion","Region":"France","Cases":418,"Deaths":0,"Recovered":300 },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":6,"Deaths":0,"Recovered":6 },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":1,"Deaths":0,"Recovered":0 },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":366,"Deaths":5,"Recovered":0 },
		{"Prov":"Shaanxi","Region":"China","Cases":306,"Deaths":3,"Recovered":253 },
		{"Prov":"Shandong","Region":"China","Cases":787,"Deaths":7,"Recovered":771 },
		{"Prov":"Shanghai","Region":"China","Cases":645,"Deaths":7,"Recovered":584 },
		{"Prov":"Shanxi","Region":"China","Cases":197,"Deaths":0,"Recovered":160 },
		{"Prov":"Sichuan","Region":"China","Cases":561,"Deaths":3,"Recovered":558 },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":75,"Deaths":13,"Recovered":33 },
		{"Prov":"South Australia","Region":"Australia","Cases":438,"Deaths":4,"Recovered":420 },
		{"Prov":"St Martin","Region":"France","Cases":38,"Deaths":3,"Recovered":24 },
		{"Prov":"Tasmania","Region":"Australia","Cases":218,"Deaths":11,"Recovered":137 },
		{"Prov":"Tianjin","Region":"China","Cases":190,"Deaths":3,"Recovered":183 },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":1 },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":12,"Deaths":1,"Recovered":5 },
		{"Prov":"Victoria","Region":"Australia","Cases":1354,"Deaths":18,"Recovered":1287 },
		{"Prov":"Western Australia","Region":"Australia","Cases":550,"Deaths":8,"Recovered":495 },
		{"Prov":"Xinjiang","Region":"China","Cases":76,"Deaths":3,"Recovered":73 },
		{"Prov":"Yukon","Region":"Canada","Cases":11,"Deaths":0,"Recovered":0 },
		{"Prov":"Yunnan","Region":"China","Cases":185,"Deaths":2,"Recovered":181 },
		{"Prov":"Zhejiang","Region":"China","Cases":1268,"Deaths":1,"Recovered":1262 }
		]}
