ReportDate[550] =	{"Date":"2021-09-25",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":874,"Deaths":3,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":58931,"Deaths":351,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":208,"Deaths":0,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":2022,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":900,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":235,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":33294,"Deaths":844,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1095,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":162172,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":165226,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":139771,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":98272,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":172733,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":148090,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":69079,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":34172,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":63688,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":24294,"Deaths":25554,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":47469,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":108757,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":87938,"Deaths":1836,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":237944,"Deaths":6193,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":122769,"Deaths":1977,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":426286,"Deaths":13719,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1231753,"Deaths":26833,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":924089,"Deaths":24175,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":490909,"Deaths":10382,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":581744,"Deaths":12503,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":856908,"Deaths":23352,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":355231,"Deaths":10156,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":531159,"Deaths":13522,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":372324,"Deaths":9532,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2131317,"Deaths":54337,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":589962,"Deaths":16635,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":441021,"Deaths":9292,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1502370,"Deaths":38837,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":618843,"Deaths":19683,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":318919,"Deaths":6997,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":368192,"Deaths":7333,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1432844,"Deaths":34741,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1278906,"Deaths":65613,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":265469,"Deaths":6520,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":126167,"Deaths":1992,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1188208,"Deaths":19186,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4360548,"Deaths":149078,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":277995,"Deaths":6008,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":223489,"Deaths":3768,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":288357,"Deaths":2622,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":182541,"Deaths":1922,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":60000,"Deaths":1207,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":3768,"Deaths":53,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":1668,"Deaths":7,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":918,"Deaths":2,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":6486,"Deaths":95,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":663,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":591185,"Deaths":9752,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":284,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":406429,"Deaths":11349,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":64949,"Deaths":667,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":745,"Deaths":9,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":61183,"Deaths":1246,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":98218,"Deaths":1509,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":27126,"Deaths":532,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":27313,"Deaths":353,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":8283,"Deaths":78,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":151277,"Deaths":2679,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":48667,"Deaths":1025,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":88912,"Deaths":1404,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":49330,"Deaths":693,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29247,"Deaths":498,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":101687,"Deaths":1780,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":690488,"Deaths":19170,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":35983,"Deaths":644,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":68696,"Deaths":1548,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":41386,"Deaths":810,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":49,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":123140,"Deaths":3463,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1008,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1120,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":603,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1272,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":199,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3163,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":298,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":147,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1317,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":1656,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1540,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12185,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68298,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1181,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":418,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1595,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":937,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":574,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":452,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":66,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":18,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":671,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":931,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2592,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":260,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1207,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":485,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":980,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1379,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1446,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6828,"Deaths":254,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":744801,"Deaths":16034,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":13289,"Deaths":454,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":319755,"Deaths":9439,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":156074,"Deaths":2959,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":105226,"Deaths":2544,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":100268,"Deaths":2257,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1448998,"Deaths":27461,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":22823,"Deaths":934,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":35501,"Deaths":918,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":55725,"Deaths":1527,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":88926,"Deaths":2483,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16355,"Deaths":392,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":103724,"Deaths":3730,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":263493,"Deaths":6795,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2292,"Deaths":29,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5130,"Deaths":94,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":88158,"Deaths":3137,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":42324,"Deaths":1334,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":93719,"Deaths":3312,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":87886,"Deaths":2226,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":89401,"Deaths":3014,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":90252,"Deaths":4241,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":16238,"Deaths":665,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":56133,"Deaths":1728,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":87554,"Deaths":2221,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":6860,"Deaths":134,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":225169,"Deaths":7275,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":58986,"Deaths":1620,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":107344,"Deaths":3649,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":406346,"Deaths":12876,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1750,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":2925,"Deaths":53,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":1115,"Deaths":2,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":553,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":39239,"Deaths":250,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":40178,"Deaths":611,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":53140,"Deaths":769,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":40804,"Deaths":609,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":20205,"Deaths":177,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":5959,"Deaths":72,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":53241,"Deaths":363,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1624,"Deaths":2,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":31,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":3740,"Deaths":35,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":566731,"Deaths":10645,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":721692,"Deaths":15602,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":204238,"Deaths":3624,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":115582,"Deaths":3843,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":32356,"Deaths":507,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":90732,"Deaths":1719,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":330577,"Deaths":7720,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":48364,"Deaths":1199,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":297999,"Deaths":5938,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":952603,"Deaths":17744,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":179031,"Deaths":3977,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":47160,"Deaths":1048,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":295723,"Deaths":10205,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":103491,"Deaths":3538,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":75704,"Deaths":1683,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":134501,"Deaths":4406,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":2545,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7618,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2045657,"Deaths":14125,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":54349,"Deaths":274,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":600423,"Deaths":5838,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":725937,"Deaths":9660,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":65209,"Deaths":819,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1005229,"Deaths":13564,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10670,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1438685,"Deaths":25085,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":176021,"Deaths":3299,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":825830,"Deaths":10082,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":770805,"Deaths":9810,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":218202,"Deaths":3666,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":328881,"Deaths":4421,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":348189,"Deaths":5133,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":2972620,"Deaths":37717,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":4613937,"Deaths":24438,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":20778,"Deaths":207,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10361,"Deaths":51,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":792487,"Deaths":10518,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6541119,"Deaths":138834,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":119674,"Deaths":1843,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":80638,"Deaths":1391,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":88166,"Deaths":289,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":31119,"Deaths":662,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1023735,"Deaths":8170,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":126012,"Deaths":1836,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":601468,"Deaths":16505,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":954297,"Deaths":8954,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":31226,"Deaths":385,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2655572,"Deaths":35476,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":664898,"Deaths":3912,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":84053,"Deaths":811,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1709761,"Deaths":22890,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":343474,"Deaths":7393,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1565645,"Deaths":18727,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":80964,"Deaths":2542,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":29945,"Deaths":611,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":83165,"Deaths":1392,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":455078,"Deaths":7899,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":422312,"Deaths":13458,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":113437,"Deaths":3817,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":383197,"Deaths":8632,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":112353,"Deaths":4407,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":882120,"Deaths":34012,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":113538,"Deaths":3070,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":14486,"Deaths":496,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":76655,"Deaths":1190,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":48257,"Deaths":1370,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":378173,"Deaths":11755,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":268048,"Deaths":6776,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":75023,"Deaths":1631,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":296100,"Deaths":6782,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":281024,"Deaths":7135,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":63610,"Deaths":1448,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":12103,"Deaths":474,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":467627,"Deaths":11756,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":104947,"Deaths":1126,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1853,"Deaths":26,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":5606,"Deaths":35,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":99148,"Deaths":988,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":5112,"Deaths":81,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":3008,"Deaths":36,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":73723,"Deaths":609,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":9416,"Deaths":174,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":18225,"Deaths":210,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":16532,"Deaths":171,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":21467,"Deaths":196,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":60068,"Deaths":1466,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":76991,"Deaths":1383,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":23994,"Deaths":214,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":7811,"Deaths":124,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3475,"Deaths":52,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":4671,"Deaths":36,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":9039,"Deaths":66,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":166975,"Deaths":1246,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4090,"Deaths":31,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":14231,"Deaths":135,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":35320,"Deaths":263,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":14549,"Deaths":160,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":16185,"Deaths":116,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":6104,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":8677,"Deaths":95,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":5951,"Deaths":71,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":15304,"Deaths":148,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":7754,"Deaths":58,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":8035,"Deaths":81,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":15052,"Deaths":135,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":49422,"Deaths":298,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":198101,"Deaths":2946,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4172,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":5724,"Deaths":29,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":114224,"Deaths":993,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":12169,"Deaths":99,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":1593,"Deaths":3,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":26509,"Deaths":204,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":15130,"Deaths":113,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3229,"Deaths":64,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":374298,"Deaths":2861,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1639,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":4783,"Deaths":49,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":5213,"Deaths":59,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":3524,"Deaths":57,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":5556,"Deaths":89,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":5083,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":189318,"Deaths":3109,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":130950,"Deaths":1732,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":109674,"Deaths":767,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":56760,"Deaths":838,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":96580,"Deaths":1191,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":61340,"Deaths":569,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":97958,"Deaths":809,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":3566,"Deaths":59,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":125938,"Deaths":1245,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":193187,"Deaths":2107,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":196146,"Deaths":749,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":670594,"Deaths":9053,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":52304,"Deaths":343,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":184831,"Deaths":2418,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":9949,"Deaths":148,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":6036,"Deaths":22,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":33270,"Deaths":2724,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":59949,"Deaths":9305,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":55004,"Deaths":2281,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":22373,"Deaths":1891,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":21906,"Deaths":2173,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":64836,"Deaths":7880,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":939700,"Deaths":38749,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":87778,"Deaths":7092,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":31069,"Deaths":1864,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":46849,"Deaths":2925,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":170190,"Deaths":11977,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":74098,"Deaths":5938,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":59569,"Deaths":7425,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":151925,"Deaths":15964,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":358284,"Deaths":42286,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":70080,"Deaths":7523,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":47086,"Deaths":4417,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":32438,"Deaths":2645,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":194645,"Deaths":12192,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":75097,"Deaths":5100,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":117232,"Deaths":14333,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":92324,"Deaths":5217,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":57563,"Deaths":3944,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":97954,"Deaths":6326,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":71256,"Deaths":8425,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":107077,"Deaths":8057,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":131383,"Deaths":5119,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":95184,"Deaths":6304,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":28005,"Deaths":2842,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":116027,"Deaths":13373,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":68756,"Deaths":5192,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":40208,"Deaths":3220,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":15405,"Deaths":165,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":2010,"Deaths":18,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":16339,"Deaths":160,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":39443,"Deaths":357,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":44382,"Deaths":251,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":53611,"Deaths":488,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":219895,"Deaths":2089,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":50753,"Deaths":268,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":131547,"Deaths":1691,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":312846,"Deaths":3170,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":343530,"Deaths":2725,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":129112,"Deaths":1163,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":4213,"Deaths":63,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":6261,"Deaths":15,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":154089,"Deaths":1304,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":34181,"Deaths":257,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":475251,"Deaths":4371,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":34020,"Deaths":735,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":32849,"Deaths":346,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10296,"Deaths":184,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":105021,"Deaths":915,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":173023,"Deaths":5498,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":428394,"Deaths":12553,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":455065,"Deaths":7335,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":31465,"Deaths":1250,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":76740,"Deaths":6636,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":26025,"Deaths":1500,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":114444,"Deaths":9638,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":33568,"Deaths":2096,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":65501,"Deaths":4104,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":100314,"Deaths":9936,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":73095,"Deaths":4743,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":16108,"Deaths":1151,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":35469,"Deaths":2687,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":58449,"Deaths":8318,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":85504,"Deaths":6973,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":87698,"Deaths":10143,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":61121,"Deaths":8583,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":946232,"Deaths":88314,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":44959,"Deaths":4170,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":13832,"Deaths":767,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":29499,"Deaths":1508,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":15734,"Deaths":1041,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":87051,"Deaths":11920,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":39693,"Deaths":4101,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":48460,"Deaths":3007,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":29679,"Deaths":1947,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":18679,"Deaths":1559,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":32055,"Deaths":3090,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":887,"Deaths":46,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":19400,"Deaths":413,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":76423,"Deaths":4102,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":21398,"Deaths":355,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":34892,"Deaths":438,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":88055,"Deaths":1176,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":58588,"Deaths":1636,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":64933,"Deaths":1516,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":52972,"Deaths":1132,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":64549,"Deaths":1399,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":58419,"Deaths":1831,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":22281,"Deaths":578,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":94153,"Deaths":3272,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":1778,"Deaths":16,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":33549,"Deaths":2257,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":51288,"Deaths":2465,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":21192,"Deaths":313,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":107189,"Deaths":4761,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":48196,"Deaths":1581,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":7844,"Deaths":255,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":31515,"Deaths":784,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":53628,"Deaths":720,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":30115,"Deaths":588,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":47590,"Deaths":687,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":19516,"Deaths":325,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":25195,"Deaths":580,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":64696,"Deaths":849,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":55894,"Deaths":1268,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":82599,"Deaths":780,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":38210,"Deaths":1082,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":74297,"Deaths":1095,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":56908,"Deaths":524,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":68989,"Deaths":1718,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":33146,"Deaths":759,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":72810,"Deaths":6060,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":114265,"Deaths":5717,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":32760,"Deaths":695,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":56618,"Deaths":1421,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":68009,"Deaths":2457,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":51910,"Deaths":1615,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":10929,"Deaths":249,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":19400,"Deaths":578,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":27754,"Deaths":548,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1617715,"Deaths":28670,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":442723,"Deaths":8130,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":71752,"Deaths":2043,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":2233,"Deaths":44,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":166930,"Deaths":6464,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":22605,"Deaths":605,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":43653,"Deaths":429,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":62703,"Deaths":2927,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":82648,"Deaths":2135,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":45458,"Deaths":1006,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":75613,"Deaths":1862,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":69368,"Deaths":2601,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":99178,"Deaths":4718,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":67856,"Deaths":1134,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":49485,"Deaths":763,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":136193,"Deaths":6669,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":41647,"Deaths":1080,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":611595,"Deaths":21569,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":53120,"Deaths":1178,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":32679,"Deaths":290,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":102296,"Deaths":3771,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":87263,"Deaths":2846,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":49101,"Deaths":1674,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":84094,"Deaths":2871,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":136314,"Deaths":6089,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":42881,"Deaths":878,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":26758,"Deaths":728,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":43199,"Deaths":561,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":54024,"Deaths":2968,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":65581,"Deaths":1625,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":60592,"Deaths":1918,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":26366,"Deaths":278,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":52034,"Deaths":1924,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":81488,"Deaths":2536,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":53278,"Deaths":1939,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":90311,"Deaths":2685,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":67477,"Deaths":1822,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":130551,"Deaths":4424,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":49968,"Deaths":682,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":60523,"Deaths":1173,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":67992,"Deaths":1146,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":799867,"Deaths":11089,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":160382,"Deaths":3799,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":70801,"Deaths":2066,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":98856,"Deaths":957,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":509137,"Deaths":7752,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":94681,"Deaths":987,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":45936,"Deaths":606,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":236883,"Deaths":6418,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":298925,"Deaths":7303,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":913160,"Deaths":15643,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":7516,"Deaths":127,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":102202,"Deaths":1973,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":186258,"Deaths":2623,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":39414,"Deaths":822,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":889089,"Deaths":16078,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":10946,"Deaths":106,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":140419,"Deaths":1728,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":82441,"Deaths":1244,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":259688,"Deaths":4908,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":13372,"Deaths":130,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":28367,"Deaths":351,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":36912,"Deaths":561,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4561,"Deaths":53,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":42924,"Deaths":324,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":13076,"Deaths":126,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":45235,"Deaths":561,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":25238,"Deaths":249,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":23372,"Deaths":324,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":27321,"Deaths":276,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":33718,"Deaths":349,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":44323,"Deaths":652,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":164165,"Deaths":1775,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":26944,"Deaths":481,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":273337,"Deaths":4412,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":42089,"Deaths":545,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":21395,"Deaths":221,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":25303,"Deaths":190,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":27473,"Deaths":481,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":29360,"Deaths":355,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":200922,"Deaths":2405,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":85731,"Deaths":1345,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":60464,"Deaths":1405,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":87108,"Deaths":1965,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":77441,"Deaths":2533,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":145795,"Deaths":4805,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":98981,"Deaths":2580,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":90685,"Deaths":2179,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":162009,"Deaths":3869,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":41114,"Deaths":1303,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":94273,"Deaths":1990,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":232495,"Deaths":5364,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":132930,"Deaths":2855,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":21522,"Deaths":886,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":32435,"Deaths":1070,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":147835,"Deaths":3836,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":72948,"Deaths":1927,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":151288,"Deaths":3217,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":81251,"Deaths":1922,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":83562,"Deaths":1250,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":29877,"Deaths":1112,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":82178,"Deaths":1404,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":75082,"Deaths":1275,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":74881,"Deaths":1769,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":65067,"Deaths":1232,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":63473,"Deaths":1628,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":111409,"Deaths":2594,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":93234,"Deaths":1887,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":364,"Deaths":1,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":4982,"Deaths":52,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2642,"Deaths":37,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":795,"Deaths":2,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":11466,"Deaths":97,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":6507849,"Deaths":119201,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":67,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":5510,"Deaths":97,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":7364,"Deaths":51,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":33,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":231696,"Deaths":2533,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":553350,"Deaths":8532,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":2830,"Deaths":22,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":338338,"Deaths":5839,"Recovered":"" }
		]}
