ReportDate[671] =	{"Date":"2022-01-24",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":31941,"Deaths":25,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":994277,"Deaths":1139,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":9702,"Deaths":2,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":344844,"Deaths":129,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":103175,"Deaths":74,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":25884,"Deaths":16,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":775888,"Deaths":1836,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1415,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":414108,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":347685,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":356950,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":259207,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":329898,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":285490,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":190048,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":70855,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":127242,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":44244,"Deaths":28835,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":108776,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":296216,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":95091,"Deaths":1857,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":251188,"Deaths":6409,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":140462,"Deaths":2039,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":495528,"Deaths":13892,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1319176,"Deaths":27791,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":1032651,"Deaths":25039,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":568433,"Deaths":11143,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":742822,"Deaths":13429,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":1006494,"Deaths":24870,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":378988,"Deaths":10452,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":601453,"Deaths":14205,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":402729,"Deaths":9796,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2514049,"Deaths":56965,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":639755,"Deaths":17296,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":479952,"Deaths":9640,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1827077,"Deaths":41005,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":669804,"Deaths":20590,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":338895,"Deaths":7351,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":404907,"Deaths":7643,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1704958,"Deaths":36644,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1613260,"Deaths":69689,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":303115,"Deaths":6810,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":137456,"Deaths":2086,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1368213,"Deaths":20384,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4565699,"Deaths":156551,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":284333,"Deaths":6075,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":255544,"Deaths":3985,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":466616,"Deaths":3429,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":308079,"Deaths":2529,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":116133,"Deaths":1515,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":26391,"Deaths":212,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":14522,"Deaths":30,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":4680,"Deaths":14,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":34689,"Deaths":128,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":1358,"Deaths":5,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":971033,"Deaths":10702,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":6282,"Deaths":6,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":838436,"Deaths":12851,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":110399,"Deaths":975,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":2959,"Deaths":16,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":79735,"Deaths":1307,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":112694,"Deaths":1574,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":37097,"Deaths":551,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":34033,"Deaths":387,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":11463,"Deaths":101,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":176056,"Deaths":2906,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":61735,"Deaths":1118,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":103689,"Deaths":1565,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":57200,"Deaths":746,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":35774,"Deaths":517,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":114121,"Deaths":1877,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":823844,"Deaths":20040,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":42192,"Deaths":681,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":77200,"Deaths":1643,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":62169,"Deaths":846,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":59,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":155129,"Deaths":3676,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1009,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1282,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":611,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1453,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":356,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3726,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":700,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":160,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1463,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":2035,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":2643,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":13104,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68320,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1230,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":1191,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1629,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":959,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":590,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":810,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":79,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":122,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":30,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":2826,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":1070,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":3679,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":267,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1372,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":1013,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":987,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1867,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":2114,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":7298,"Deaths":260,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":891232,"Deaths":17325,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":15001,"Deaths":493,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":383480,"Deaths":9803,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":192349,"Deaths":3132,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":118565,"Deaths":2620,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":114485,"Deaths":2341,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1634327,"Deaths":27953,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":24016,"Deaths":955,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":38333,"Deaths":948,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":68742,"Deaths":1645,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":100561,"Deaths":2588,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":18150,"Deaths":413,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":114254,"Deaths":3776,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":295318,"Deaths":6910,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2671,"Deaths":35,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5372,"Deaths":97,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":95869,"Deaths":3268,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":51603,"Deaths":1462,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":109865,"Deaths":3514,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":98053,"Deaths":2342,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":101543,"Deaths":3096,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":109363,"Deaths":4784,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":19325,"Deaths":731,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":67928,"Deaths":1922,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":102180,"Deaths":2333,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":9785,"Deaths":152,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":263010,"Deaths":7644,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":63193,"Deaths":1636,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":119645,"Deaths":3738,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":0,"Deaths":533,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":520856,"Deaths":13952,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1833,"Deaths":18,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":3193,"Deaths":58,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":14865,"Deaths":17,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":9823,"Deaths":4,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":72819,"Deaths":359,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":47656,"Deaths":636,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":73660,"Deaths":835,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":77075,"Deaths":821,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":35966,"Deaths":187,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":16000,"Deaths":282,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":133617,"Deaths":462,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":3282,"Deaths":6,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":696,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":9143,"Deaths":60,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":1234263,"Deaths":13574,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":1602042,"Deaths":20344,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":467911,"Deaths":4088,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":307540,"Deaths":4971,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":77594,"Deaths":641,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":212852,"Deaths":2085,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":624006,"Deaths":8739,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":130177,"Deaths":1617,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":577236,"Deaths":7059,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":1749057,"Deaths":20941,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":343540,"Deaths":4770,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":92339,"Deaths":1317,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":698375,"Deaths":13979,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":250415,"Deaths":4548,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":193601,"Deaths":1939,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":310918,"Deaths":6355,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":37637,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":9452,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2195136,"Deaths":14549,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":60072,"Deaths":283,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":698713,"Deaths":6319,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":813343,"Deaths":12193,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":86260,"Deaths":1103,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1100218,"Deaths":13746,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":11214,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1797471,"Deaths":25650,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":230825,"Deaths":3615,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":1076360,"Deaths":10274,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":914826,"Deaths":10194,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":262087,"Deaths":3944,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":402596,"Deaths":4613,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":421838,"Deaths":5272,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":3564108,"Deaths":38614,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":5669611,"Deaths":51987,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":24818,"Deaths":222,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10812,"Deaths":52,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":904744,"Deaths":10576,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":7535511,"Deaths":142151,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":130490,"Deaths":2027,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":88764,"Deaths":1498,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":162371,"Deaths":586,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":33654,"Deaths":707,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1211951,"Deaths":8525,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":153343,"Deaths":1908,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":719142,"Deaths":17023,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":1139382,"Deaths":9118,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":37096,"Deaths":423,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":3164205,"Deaths":37264,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":738795,"Deaths":4075,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":98899,"Deaths":879,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1957839,"Deaths":23073,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":403465,"Deaths":7491,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1969791,"Deaths":20375,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":193172,"Deaths":2758,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":56779,"Deaths":669,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":160262,"Deaths":1801,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":952719,"Deaths":8925,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":948126,"Deaths":14811,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":241016,"Deaths":4407,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":793727,"Deaths":9668,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":264328,"Deaths":4797,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":1987944,"Deaths":36614,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":224393,"Deaths":3356,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":27264,"Deaths":522,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":147428,"Deaths":1342,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":111193,"Deaths":1461,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":796880,"Deaths":12481,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":548925,"Deaths":7135,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":117095,"Deaths":1807,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":575344,"Deaths":8214,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":669850,"Deaths":8058,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":142714,"Deaths":1594,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":27035,"Deaths":500,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":1015150,"Deaths":12955,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":135978,"Deaths":1173,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":2623,"Deaths":27,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":7911,"Deaths":39,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":121548,"Deaths":1036,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":8268,"Deaths":82,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":4361,"Deaths":38,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":97062,"Deaths":633,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":10786,"Deaths":176,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":23822,"Deaths":220,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":23313,"Deaths":184,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":40787,"Deaths":217,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":75006,"Deaths":1480,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":102364,"Deaths":1403,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":29958,"Deaths":220,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":9913,"Deaths":140,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3861,"Deaths":53,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":6317,"Deaths":39,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":12738,"Deaths":66,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":203351,"Deaths":1330,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4887,"Deaths":33,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":21468,"Deaths":139,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":50112,"Deaths":294,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":18426,"Deaths":168,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":18282,"Deaths":118,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":8726,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":13843,"Deaths":97,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":10271,"Deaths":74,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":20445,"Deaths":152,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":12955,"Deaths":63,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":10855,"Deaths":84,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":20441,"Deaths":136,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":75927,"Deaths":399,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":267486,"Deaths":3079,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4463,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":8694,"Deaths":32,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":141108,"Deaths":1061,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":17991,"Deaths":105,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":3561,"Deaths":6,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":36700,"Deaths":210,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":20008,"Deaths":121,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3907,"Deaths":66,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":471650,"Deaths":3185,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":2576,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":5662,"Deaths":52,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":8090,"Deaths":64,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":4378,"Deaths":56,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":10541,"Deaths":95,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":6954,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":254461,"Deaths":3904,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":174374,"Deaths":2186,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":175919,"Deaths":1272,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":79885,"Deaths":969,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":117450,"Deaths":1334,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":100139,"Deaths":799,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":132199,"Deaths":1427,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":7492,"Deaths":138,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":165809,"Deaths":1767,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":245763,"Deaths":2821,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":252709,"Deaths":1621,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":806648,"Deaths":10041,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":84777,"Deaths":754,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":217514,"Deaths":2696,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":11033,"Deaths":151,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":9987,"Deaths":22,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":46578,"Deaths":3140,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":114027,"Deaths":11434,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":84646,"Deaths":2475,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":27874,"Deaths":2111,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":25699,"Deaths":2304,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":100275,"Deaths":9044,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":1164458,"Deaths":40670,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":127944,"Deaths":8037,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":41547,"Deaths":2055,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":61737,"Deaths":3240,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":235117,"Deaths":13726,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":85782,"Deaths":6361,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":73000,"Deaths":7963,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":192761,"Deaths":18027,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":445728,"Deaths":45081,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":81591,"Deaths":8320,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":55946,"Deaths":4972,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":45742,"Deaths":2942,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":247370,"Deaths":13958,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":94932,"Deaths":5702,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":139870,"Deaths":15811,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":117830,"Deaths":5704,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":79255,"Deaths":4173,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":142959,"Deaths":6959,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":95650,"Deaths":9102,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":140997,"Deaths":9394,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":171994,"Deaths":5802,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":123140,"Deaths":7230,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":33298,"Deaths":3004,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":137762,"Deaths":15226,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":92198,"Deaths":5785,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":58060,"Deaths":3549,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":32405,"Deaths":193,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":6507,"Deaths":27,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":36092,"Deaths":216,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":79715,"Deaths":429,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":91749,"Deaths":314,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":117695,"Deaths":586,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":436512,"Deaths":2616,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":98542,"Deaths":343,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":268127,"Deaths":2082,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":587473,"Deaths":3573,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":692829,"Deaths":3157,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":253617,"Deaths":1350,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":9076,"Deaths":78,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":25083,"Deaths":16,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":319869,"Deaths":1483,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":81584,"Deaths":361,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":901504,"Deaths":4909,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":2,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":35474,"Deaths":752,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":33975,"Deaths":367,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10510,"Deaths":187,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":120128,"Deaths":976,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":185683,"Deaths":5977,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":466164,"Deaths":13117,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":529218,"Deaths":7746,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":36021,"Deaths":1295,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":98814,"Deaths":6821,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":29930,"Deaths":1542,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":150382,"Deaths":9808,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":40217,"Deaths":2184,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":80452,"Deaths":4226,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":125469,"Deaths":10198,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":97850,"Deaths":4883,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":18983,"Deaths":1194,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":42775,"Deaths":2746,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":75935,"Deaths":8655,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":103914,"Deaths":7150,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":114470,"Deaths":10483,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":84124,"Deaths":8770,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":1295823,"Deaths":90230,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":49581,"Deaths":4292,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":15358,"Deaths":789,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":35737,"Deaths":1548,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":18772,"Deaths":1057,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":116622,"Deaths":12387,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":51508,"Deaths":4323,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":54281,"Deaths":3052,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":39814,"Deaths":1998,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":20592,"Deaths":1607,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":34228,"Deaths":3085,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":144608,"Deaths":81,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":29019,"Deaths":809,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":127446,"Deaths":7175,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":25973,"Deaths":546,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":58251,"Deaths":643,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":129816,"Deaths":1556,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":85746,"Deaths":2612,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":127662,"Deaths":4650,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":84931,"Deaths":1884,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":100631,"Deaths":3159,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":80105,"Deaths":2574,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":33042,"Deaths":989,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":153222,"Deaths":6425,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":3022,"Deaths":39,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":48418,"Deaths":4179,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":69563,"Deaths":3306,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":30432,"Deaths":501,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":165169,"Deaths":7315,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":71010,"Deaths":2670,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":12103,"Deaths":445,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":44092,"Deaths":1555,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":87364,"Deaths":1394,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":34773,"Deaths":767,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":68513,"Deaths":1278,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":24821,"Deaths":527,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":33805,"Deaths":926,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":94433,"Deaths":1288,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":91373,"Deaths":1847,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":131371,"Deaths":1323,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":56072,"Deaths":2112,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":103520,"Deaths":2137,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":84010,"Deaths":806,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":100507,"Deaths":2753,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":50207,"Deaths":1156,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":131677,"Deaths":10011,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":180883,"Deaths":9306,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":52768,"Deaths":1041,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":84609,"Deaths":2152,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":109125,"Deaths":3117,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":88095,"Deaths":2983,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":14117,"Deaths":356,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":30815,"Deaths":962,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":42180,"Deaths":1118,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":2194045,"Deaths":38439,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":699014,"Deaths":13078,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":95015,"Deaths":2888,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":3645,"Deaths":89,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":243364,"Deaths":10378,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":32712,"Deaths":1065,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":68643,"Deaths":820,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":100837,"Deaths":4540,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":137536,"Deaths":3436,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":74568,"Deaths":1602,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":111872,"Deaths":3572,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":106198,"Deaths":4838,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":170965,"Deaths":7728,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":109340,"Deaths":1672,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":73925,"Deaths":1391,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":205232,"Deaths":9959,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":64233,"Deaths":2813,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":930172,"Deaths":29479,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":84107,"Deaths":1848,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":45172,"Deaths":613,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":209376,"Deaths":6617,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":138838,"Deaths":5297,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":88218,"Deaths":2530,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":135741,"Deaths":6383,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":211712,"Deaths":9906,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":65345,"Deaths":1886,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":45525,"Deaths":1561,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":64894,"Deaths":696,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":80657,"Deaths":4524,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":104319,"Deaths":2438,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":96460,"Deaths":3681,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":32524,"Deaths":332,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":82486,"Deaths":3298,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":123722,"Deaths":4032,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":86299,"Deaths":3053,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":135365,"Deaths":5907,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":103342,"Deaths":3147,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":202836,"Deaths":7212,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":65329,"Deaths":976,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":90690,"Deaths":2055,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":99063,"Deaths":2007,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":1202406,"Deaths":11831,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":337242,"Deaths":4332,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":160027,"Deaths":2253,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":209425,"Deaths":1110,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":993167,"Deaths":8374,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":245215,"Deaths":1344,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":100911,"Deaths":655,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":408536,"Deaths":6745,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":568136,"Deaths":7808,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":1851309,"Deaths":16247,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":16562,"Deaths":139,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":197589,"Deaths":2100,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":407567,"Deaths":2874,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":79208,"Deaths":879,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":1423318,"Deaths":16482,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":18089,"Deaths":125,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":294595,"Deaths":1922,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":195469,"Deaths":1379,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":572119,"Deaths":5395,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":19769,"Deaths":140,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":45086,"Deaths":374,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":52317,"Deaths":584,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":7739,"Deaths":55,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":71763,"Deaths":345,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":23863,"Deaths":131,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":63572,"Deaths":579,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":37756,"Deaths":267,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":33736,"Deaths":337,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":36152,"Deaths":300,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":55446,"Deaths":368,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":62814,"Deaths":677,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":253444,"Deaths":1893,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":43880,"Deaths":500,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":447555,"Deaths":4674,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":63853,"Deaths":566,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":38430,"Deaths":235,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":37672,"Deaths":206,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":37627,"Deaths":489,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":51299,"Deaths":394,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":300232,"Deaths":2560,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":133630,"Deaths":2744,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":99175,"Deaths":2562,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":127547,"Deaths":3093,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":130137,"Deaths":4654,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":248763,"Deaths":9092,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":173907,"Deaths":5267,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":147467,"Deaths":3196,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":256092,"Deaths":6543,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":81541,"Deaths":2744,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":155524,"Deaths":3445,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":353224,"Deaths":8444,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":192653,"Deaths":4799,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":34711,"Deaths":1624,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":62006,"Deaths":2255,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":240492,"Deaths":6155,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":118691,"Deaths":3377,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":249822,"Deaths":5684,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":147263,"Deaths":3924,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":133959,"Deaths":2344,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":55136,"Deaths":1935,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":142511,"Deaths":2937,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":116564,"Deaths":2206,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":121620,"Deaths":3298,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":106987,"Deaths":2234,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":93417,"Deaths":2516,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":185230,"Deaths":5467,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":147574,"Deaths":3332,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":2187,"Deaths":7,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":10262,"Deaths":114,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":5649,"Deaths":47,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":13734,"Deaths":15,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":39152,"Deaths":126,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":13558510,"Deaths":133864,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":86,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":11937,"Deaths":100,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":20586,"Deaths":70,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":158,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":510073,"Deaths":3072,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":1124048,"Deaths":10198,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":5570,"Deaths":34,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":761054,"Deaths":6782,"Recovered":"" }
		]}
