ReportDate[619] =	{"Date":"2021-12-03",
		"Data":[
		{"Prov":"Australian Capital Territory","Region":"Australia","Cases":2153,"Deaths":14,"Recovered":"" },
		{"Prov":"New South Wales","Region":"Australia","Cases":82837,"Deaths":629,"Recovered":"" },
		{"Prov":"Northern Territory","Region":"Australia","Cases":293,"Deaths":0,"Recovered":"" },
		{"Prov":"Queensland","Region":"Australia","Cases":2146,"Deaths":7,"Recovered":"" },
		{"Prov":"South Australia","Region":"Australia","Cases":957,"Deaths":4,"Recovered":"" },
		{"Prov":"Tasmania","Region":"Australia","Cases":240,"Deaths":13,"Recovered":"" },
		{"Prov":"Victoria","Region":"Australia","Cases":126839,"Deaths":1366,"Recovered":"" },
		{"Prov":"Western Australia","Region":"Australia","Cases":1122,"Deaths":9,"Recovered":"" },
		{"Prov":"Antwerp","Region":"Belgium","Cases":263191,"Deaths":0,"Recovered":"" },
		{"Prov":"Brussels","Region":"Belgium","Cases":215714,"Deaths":0,"Recovered":"" },
		{"Prov":"East Flanders","Region":"Belgium","Cases":224501,"Deaths":0,"Recovered":"" },
		{"Prov":"Flemish Brabant","Region":"Belgium","Cases":155831,"Deaths":0,"Recovered":"" },
		{"Prov":"Hainaut","Region":"Belgium","Cases":222228,"Deaths":0,"Recovered":"" },
		{"Prov":"Liege","Region":"Belgium","Cases":204284,"Deaths":0,"Recovered":"" },
		{"Prov":"Limburg","Region":"Belgium","Cases":118318,"Deaths":0,"Recovered":"" },
		{"Prov":"Luxembourg","Region":"Belgium","Cases":48861,"Deaths":0,"Recovered":"" },
		{"Prov":"Namur","Region":"Belgium","Cases":88638,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"Belgium","Cases":30380,"Deaths":27167,"Recovered":"" },
		{"Prov":"Walloon Brabant","Region":"Belgium","Cases":68663,"Deaths":0,"Recovered":"" },
		{"Prov":"West Flanders","Region":"Belgium","Cases":186858,"Deaths":0,"Recovered":"" },
		{"Prov":"Acre","Region":"Brazil","Cases":88225,"Deaths":1849,"Recovered":"" },
		{"Prov":"Alagoas","Region":"Brazil","Cases":241565,"Deaths":6358,"Recovered":"" },
		{"Prov":"Amapa","Region":"Brazil","Cases":124825,"Deaths":2004,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Brazil","Cases":430350,"Deaths":13808,"Recovered":"" },
		{"Prov":"Bahia","Region":"Brazil","Cases":1262066,"Deaths":27336,"Recovered":"" },
		{"Prov":"Ceara","Region":"Brazil","Cases":951638,"Deaths":24667,"Recovered":"" },
		{"Prov":"Distrito Federal","Region":"Brazil","Cases":518062,"Deaths":11043,"Recovered":"" },
		{"Prov":"Espirito Santo","Region":"Brazil","Cases":621832,"Deaths":13203,"Recovered":"" },
		{"Prov":"Goias","Region":"Brazil","Cases":939288,"Deaths":24564,"Recovered":"" },
		{"Prov":"Maranhao","Region":"Brazil","Cases":365929,"Deaths":10304,"Recovered":"" },
		{"Prov":"Mato Grosso","Region":"Brazil","Cases":550013,"Deaths":13750,"Recovered":"" },
		{"Prov":"Mato Grosso do Sul","Region":"Brazil","Cases":379140,"Deaths":9687,"Recovered":"" },
		{"Prov":"Minas Gerais","Region":"Brazil","Cases":2210587,"Deaths":56301,"Recovered":"" },
		{"Prov":"Para","Region":"Brazil","Cases":610832,"Deaths":16932,"Recovered":"" },
		{"Prov":"Paraiba","Region":"Brazil","Cases":461374,"Deaths":9538,"Recovered":"" },
		{"Prov":"Parana","Region":"Brazil","Cases":1581059,"Deaths":40804,"Recovered":"" },
		{"Prov":"Pernambuco","Region":"Brazil","Cases":640777,"Deaths":20263,"Recovered":"" },
		{"Prov":"Piaui","Region":"Brazil","Cases":332271,"Deaths":7200,"Recovered":"" },
		{"Prov":"Rio Grande do Norte","Region":"Brazil","Cases":382811,"Deaths":7503,"Recovered":"" },
		{"Prov":"Rio Grande do Sul","Region":"Brazil","Cases":1494207,"Deaths":36183,"Recovered":"" },
		{"Prov":"Rio de Janeiro","Region":"Brazil","Cases":1346494,"Deaths":69124,"Recovered":"" },
		{"Prov":"Rondonia","Region":"Brazil","Cases":278882,"Deaths":6650,"Recovered":"" },
		{"Prov":"Roraima","Region":"Brazil","Cases":128545,"Deaths":2055,"Recovered":"" },
		{"Prov":"Santa Catarina","Region":"Brazil","Cases":1234592,"Deaths":20028,"Recovered":"" },
		{"Prov":"Sao Paulo","Region":"Brazil","Cases":4442612,"Deaths":154279,"Recovered":"" },
		{"Prov":"Sergipe","Region":"Brazil","Cases":278292,"Deaths":6046,"Recovered":"" },
		{"Prov":"Tocantins","Region":"Brazil","Cases":233141,"Deaths":3921,"Recovered":"" },
		{"Prov":"Alberta","Region":"Canada","Cases":336392,"Deaths":3258,"Recovered":"" },
		{"Prov":"British Columbia","Region":"Canada","Cases":219584,"Deaths":2351,"Recovered":"" },
		{"Prov":"Diamond Princess","Region":"Canada","Cases":0,"Deaths":1,"Recovered":"" },
		{"Prov":"Grand Princess","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Manitoba","Region":"Canada","Cases":68308,"Deaths":1328,"Recovered":"" },
		{"Prov":"New Brunswick","Region":"Canada","Cases":8603,"Deaths":132,"Recovered":"" },
		{"Prov":"Newfoundland and Labrador","Region":"Canada","Cases":2064,"Deaths":18,"Recovered":"" },
		{"Prov":"Northwest Territories","Region":"Canada","Cases":2069,"Deaths":12,"Recovered":"" },
		{"Prov":"Nova Scotia","Region":"Canada","Cases":8381,"Deaths":110,"Recovered":"" },
		{"Prov":"Nunavut","Region":"Canada","Cases":674,"Deaths":4,"Recovered":"" },
		{"Prov":"Ontario","Region":"Canada","Cases":629723,"Deaths":10069,"Recovered":"" },
		{"Prov":"Prince Edward Island","Region":"Canada","Cases":372,"Deaths":0,"Recovered":"" },
		{"Prov":"Quebec","Region":"Canada","Cases":451867,"Deaths":11585,"Recovered":"" },
		{"Prov":"Repatriated Travellers","Region":"Canada","Cases":13,"Deaths":0,"Recovered":"" },
		{"Prov":"Saskatchewan","Region":"Canada","Cases":81225,"Deaths":929,"Recovered":"" },
		{"Prov":"Yukon","Region":"Canada","Cases":1537,"Deaths":14,"Recovered":"" },
		{"Prov":"Antofagasta","Region":"Chile","Cases":65565,"Deaths":1270,"Recovered":"" },
		{"Prov":"Araucania","Region":"Chile","Cases":101857,"Deaths":1534,"Recovered":"" },
		{"Prov":"Arica y Parinacota","Region":"Chile","Cases":28588,"Deaths":542,"Recovered":"" },
		{"Prov":"Atacama","Region":"Chile","Cases":29780,"Deaths":371,"Recovered":"" },
		{"Prov":"Aysen","Region":"Chile","Cases":9844,"Deaths":83,"Recovered":"" },
		{"Prov":"Biobio","Region":"Chile","Cases":161950,"Deaths":2744,"Recovered":"" },
		{"Prov":"Coquimbo","Region":"Chile","Cases":53218,"Deaths":1063,"Recovered":"" },
		{"Prov":"Los Lagos","Region":"Chile","Cases":95151,"Deaths":1441,"Recovered":"" },
		{"Prov":"Los Rios","Region":"Chile","Cases":52018,"Deaths":706,"Recovered":"" },
		{"Prov":"Magallanes","Region":"Chile","Cases":29697,"Deaths":501,"Recovered":"" },
		{"Prov":"Maule","Region":"Chile","Cases":108041,"Deaths":1824,"Recovered":"" },
		{"Prov":"Metropolitana","Region":"Chile","Cases":743411,"Deaths":19713,"Recovered":"" },
		{"Prov":"Nuble","Region":"Chile","Cases":38435,"Deaths":662,"Recovered":"" },
		{"Prov":"OHiggins","Region":"Chile","Cases":72386,"Deaths":1609,"Recovered":"" },
		{"Prov":"Tarapaca","Region":"Chile","Cases":44204,"Deaths":816,"Recovered":"" },
		{"Prov":"Unknown","Region":"Chile","Cases":46,"Deaths":0,"Recovered":"" },
		{"Prov":"Valparaiso","Region":"Chile","Cases":134393,"Deaths":3560,"Recovered":"" },
		{"Prov":"Anhui","Region":"China","Cases":1008,"Deaths":6,"Recovered":"" },
		{"Prov":"Beijing","Region":"China","Cases":1194,"Deaths":9,"Recovered":"" },
		{"Prov":"Chongqing","Region":"China","Cases":610,"Deaths":6,"Recovered":"" },
		{"Prov":"Fujian","Region":"China","Cases":1322,"Deaths":1,"Recovered":"" },
		{"Prov":"Gansu","Region":"China","Cases":344,"Deaths":2,"Recovered":"" },
		{"Prov":"Guangdong","Region":"China","Cases":3322,"Deaths":8,"Recovered":"" },
		{"Prov":"Guangxi","Region":"China","Cases":416,"Deaths":2,"Recovered":"" },
		{"Prov":"Guizhou","Region":"China","Cases":159,"Deaths":2,"Recovered":"" },
		{"Prov":"Hainan","Region":"China","Cases":190,"Deaths":6,"Recovered":"" },
		{"Prov":"Hebei","Region":"China","Cases":1457,"Deaths":7,"Recovered":"" },
		{"Prov":"Heilongjiang","Region":"China","Cases":2007,"Deaths":13,"Recovered":"" },
		{"Prov":"Henan","Region":"China","Cases":1637,"Deaths":22,"Recovered":"" },
		{"Prov":"Hong Kong","Region":"China","Cases":12448,"Deaths":213,"Recovered":"" },
		{"Prov":"Hubei","Region":"China","Cases":68311,"Deaths":4512,"Recovered":"" },
		{"Prov":"Hunan","Region":"China","Cases":1199,"Deaths":4,"Recovered":"" },
		{"Prov":"Inner Mongolia","Region":"China","Cases":920,"Deaths":1,"Recovered":"" },
		{"Prov":"Jiangsu","Region":"China","Cases":1619,"Deaths":0,"Recovered":"" },
		{"Prov":"Jiangxi","Region":"China","Cases":959,"Deaths":1,"Recovered":"" },
		{"Prov":"Jilin","Region":"China","Cases":585,"Deaths":3,"Recovered":"" },
		{"Prov":"Liaoning","Region":"China","Cases":784,"Deaths":2,"Recovered":"" },
		{"Prov":"Macau","Region":"China","Cases":77,"Deaths":0,"Recovered":"" },
		{"Prov":"Ningxia","Region":"China","Cases":122,"Deaths":0,"Recovered":"" },
		{"Prov":"Qinghai","Region":"China","Cases":30,"Deaths":0,"Recovered":"" },
		{"Prov":"Shaanxi","Region":"China","Cases":709,"Deaths":3,"Recovered":"" },
		{"Prov":"Shandong","Region":"China","Cases":1021,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanghai","Region":"China","Cases":2873,"Deaths":7,"Recovered":"" },
		{"Prov":"Shanxi","Region":"China","Cases":265,"Deaths":0,"Recovered":"" },
		{"Prov":"Sichuan","Region":"China","Cases":1277,"Deaths":3,"Recovered":"" },
		{"Prov":"Tianjin","Region":"China","Cases":533,"Deaths":3,"Recovered":"" },
		{"Prov":"Tibet","Region":"China","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Unknown","Region":"China","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Xinjiang","Region":"China","Cases":981,"Deaths":3,"Recovered":"" },
		{"Prov":"Yunnan","Region":"China","Cases":1727,"Deaths":2,"Recovered":"" },
		{"Prov":"Zhejiang","Region":"China","Cases":1501,"Deaths":1,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Colombia","Cases":6914,"Deaths":257,"Recovered":"" },
		{"Prov":"Antioquia","Region":"Colombia","Cases":771068,"Deaths":16590,"Recovered":"" },
		{"Prov":"Arauca","Region":"Colombia","Cases":14111,"Deaths":475,"Recovered":"" },
		{"Prov":"Atlantico","Region":"Colombia","Cases":339529,"Deaths":9684,"Recovered":"" },
		{"Prov":"Bolivar","Region":"Colombia","Cases":160624,"Deaths":3029,"Recovered":"" },
		{"Prov":"Boyaca","Region":"Colombia","Cases":106425,"Deaths":2576,"Recovered":"" },
		{"Prov":"Caldas","Region":"Colombia","Cases":101305,"Deaths":2286,"Recovered":"" },
		{"Prov":"Capital District","Region":"Colombia","Cases":1463367,"Deaths":27637,"Recovered":"" },
		{"Prov":"Caqueta","Region":"Colombia","Cases":23004,"Deaths":942,"Recovered":"" },
		{"Prov":"Casanare","Region":"Colombia","Cases":35946,"Deaths":935,"Recovered":"" },
		{"Prov":"Cauca","Region":"Colombia","Cases":56918,"Deaths":1588,"Recovered":"" },
		{"Prov":"Cesar","Region":"Colombia","Cases":91946,"Deaths":2529,"Recovered":"" },
		{"Prov":"Choco","Region":"Colombia","Cases":16512,"Deaths":401,"Recovered":"" },
		{"Prov":"Cordoba","Region":"Colombia","Cases":104599,"Deaths":3742,"Recovered":"" },
		{"Prov":"Cundinamarca","Region":"Colombia","Cases":266334,"Deaths":6846,"Recovered":"" },
		{"Prov":"Guainia","Region":"Colombia","Cases":2506,"Deaths":30,"Recovered":"" },
		{"Prov":"Guaviare","Region":"Colombia","Cases":5159,"Deaths":97,"Recovered":"" },
		{"Prov":"Huila","Region":"Colombia","Cases":89040,"Deaths":3162,"Recovered":"" },
		{"Prov":"La Guajira","Region":"Colombia","Cases":45968,"Deaths":1406,"Recovered":"" },
		{"Prov":"Magdalena","Region":"Colombia","Cases":100146,"Deaths":3441,"Recovered":"" },
		{"Prov":"Meta","Region":"Colombia","Cases":90248,"Deaths":2283,"Recovered":"" },
		{"Prov":"Narino","Region":"Colombia","Cases":90456,"Deaths":3044,"Recovered":"" },
		{"Prov":"Norte de Santander","Region":"Colombia","Cases":99142,"Deaths":4547,"Recovered":"" },
		{"Prov":"Putumayo","Region":"Colombia","Cases":17149,"Deaths":688,"Recovered":"" },
		{"Prov":"Quindio","Region":"Colombia","Cases":58115,"Deaths":1806,"Recovered":"" },
		{"Prov":"Risaralda","Region":"Colombia","Cases":88549,"Deaths":2250,"Recovered":"" },
		{"Prov":"San Andres y Providencia","Region":"Colombia","Cases":8122,"Deaths":148,"Recovered":"" },
		{"Prov":"Santander","Region":"Colombia","Cases":231192,"Deaths":7399,"Recovered":"" },
		{"Prov":"Sucre","Region":"Colombia","Cases":59665,"Deaths":1627,"Recovered":"" },
		{"Prov":"Tolima","Region":"Colombia","Cases":108165,"Deaths":3682,"Recovered":"" },
		{"Prov":"Unknown","Region":"Colombia","Cases":2299,"Deaths":296,"Recovered":"" },
		{"Prov":"Valle del Cauca","Region":"Colombia","Cases":417045,"Deaths":13192,"Recovered":"" },
		{"Prov":"Vaupes","Region":"Colombia","Cases":1796,"Deaths":17,"Recovered":"" },
		{"Prov":"Vichada","Region":"Colombia","Cases":3014,"Deaths":53,"Recovered":"" },
		{"Prov":"Faroe Islands","Region":"Denmark","Cases":3796,"Deaths":13,"Recovered":"" },
		{"Prov":"Greenland","Region":"Denmark","Cases":1582,"Deaths":0,"Recovered":"" },
		{"Prov":"French Guiana","Region":"France","Cases":46094,"Deaths":328,"Recovered":"" },
		{"Prov":"French Polynesia","Region":"France","Cases":46323,"Deaths":636,"Recovered":"" },
		{"Prov":"Guadeloupe","Region":"France","Cases":55080,"Deaths":823,"Recovered":"" },
		{"Prov":"Martinique","Region":"France","Cases":45600,"Deaths":721,"Recovered":"" },
		{"Prov":"Mayotte","Region":"France","Cases":20973,"Deaths":185,"Recovered":"" },
		{"Prov":"New Caledonia","Region":"France","Cases":12331,"Deaths":278,"Recovered":"" },
		{"Prov":"Reunion","Region":"France","Cases":61188,"Deaths":384,"Recovered":"" },
		{"Prov":"Saint Barthelemy","Region":"France","Cases":1672,"Deaths":6,"Recovered":"" },
		{"Prov":"Saint Pierre and Miquelon","Region":"France","Cases":86,"Deaths":0,"Recovered":"" },
		{"Prov":"St Martin","Region":"France","Cases":4031,"Deaths":56,"Recovered":"" },
		{"Prov":"Wallis and Futuna","Region":"France","Cases":454,"Deaths":7,"Recovered":"" },
		{"Prov":"Baden-Wurttemberg","Region":"Germany","Cases":869103,"Deaths":11943,"Recovered":"" },
		{"Prov":"Bayern","Region":"Germany","Cases":1177379,"Deaths":17908,"Recovered":"" },
		{"Prov":"Berlin","Region":"Germany","Cases":284312,"Deaths":3853,"Recovered":"" },
		{"Prov":"Brandenburg","Region":"Germany","Cases":189717,"Deaths":4199,"Recovered":"" },
		{"Prov":"Bremen","Region":"Germany","Cases":40552,"Deaths":555,"Recovered":"" },
		{"Prov":"Hamburg","Region":"Germany","Cases":116849,"Deaths":1902,"Recovered":"" },
		{"Prov":"Hessen","Region":"Germany","Cases":425329,"Deaths":8205,"Recovered":"" },
		{"Prov":"Mecklenburg-Vorpommern","Region":"Germany","Cases":76525,"Deaths":1347,"Recovered":"" },
		{"Prov":"Niedersachsen","Region":"Germany","Cases":387796,"Deaths":6430,"Recovered":"" },
		{"Prov":"Nordrhein-Westfalen","Region":"Germany","Cases":1210661,"Deaths":19182,"Recovered":"" },
		{"Prov":"Rheinland-Pfalz","Region":"Germany","Cases":242927,"Deaths":4319,"Recovered":"" },
		{"Prov":"Saarland","Region":"Germany","Cases":63912,"Deaths":1124,"Recovered":"" },
		{"Prov":"Sachsen","Region":"Germany","Cases":533740,"Deaths":11209,"Recovered":"" },
		{"Prov":"Sachsen-Anhalt","Region":"Germany","Cases":170808,"Deaths":3846,"Recovered":"" },
		{"Prov":"Schleswig-Holstein","Region":"Germany","Cases":99517,"Deaths":1807,"Recovered":"" },
		{"Prov":"Thuringen","Region":"Germany","Cases":227014,"Deaths":5122,"Recovered":"" },
		{"Prov":"Unknown","Region":"Germany","Cases":18351,"Deaths":0,"Recovered":"" },
		{"Prov":"Andaman and Nicobar Islands","Region":"India","Cases":7688,"Deaths":129,"Recovered":"" },
		{"Prov":"Andhra Pradesh","Region":"India","Cases":2073390,"Deaths":14445,"Recovered":"" },
		{"Prov":"Arunachal Pradesh","Region":"India","Cases":55286,"Deaths":280,"Recovered":"" },
		{"Prov":"Assam","Region":"India","Cases":617306,"Deaths":6113,"Recovered":"" },
		{"Prov":"Bihar","Region":"India","Cases":726230,"Deaths":9664,"Recovered":"" },
		{"Prov":"Chandigarh","Region":"India","Cases":65478,"Deaths":820,"Recovered":"" },
		{"Prov":"Chhattisgarh","Region":"India","Cases":1006898,"Deaths":13593,"Recovered":"" },
		{"Prov":"Dadra and Nagar Haveli and Daman and Diu","Region":"India","Cases":10683,"Deaths":4,"Recovered":"" },
		{"Prov":"Delhi","Region":"India","Cases":1441244,"Deaths":25098,"Recovered":"" },
		{"Prov":"Goa","Region":"India","Cases":179088,"Deaths":3385,"Recovered":"" },
		{"Prov":"Gujarat","Region":"India","Cases":827615,"Deaths":10094,"Recovered":"" },
		{"Prov":"Haryana","Region":"India","Cases":771780,"Deaths":10054,"Recovered":"" },
		{"Prov":"Himachal Pradesh","Region":"India","Cases":227405,"Deaths":3852,"Recovered":"" },
		{"Prov":"Jammu and Kashmir","Region":"India","Cases":337444,"Deaths":4479,"Recovered":"" },
		{"Prov":"Jharkhand","Region":"India","Cases":349282,"Deaths":5141,"Recovered":"" },
		{"Prov":"Karnataka","Region":"India","Cases":2997246,"Deaths":38220,"Recovered":"" },
		{"Prov":"Kerala","Region":"India","Cases":5156914,"Deaths":41124,"Recovered":"" },
		{"Prov":"Ladakh","Region":"India","Cases":21669,"Deaths":215,"Recovered":"" },
		{"Prov":"Lakshadweep","Region":"India","Cases":10397,"Deaths":51,"Recovered":"" },
		{"Prov":"Madhya Pradesh","Region":"India","Cases":793214,"Deaths":10528,"Recovered":"" },
		{"Prov":"Maharashtra","Region":"India","Cases":6637289,"Deaths":141149,"Recovered":"" },
		{"Prov":"Manipur","Region":"India","Cases":125297,"Deaths":1980,"Recovered":"" },
		{"Prov":"Meghalaya","Region":"India","Cases":84556,"Deaths":1475,"Recovered":"" },
		{"Prov":"Mizoram","Region":"India","Cases":136080,"Deaths":504,"Recovered":"" },
		{"Prov":"Nagaland","Region":"India","Cases":32130,"Deaths":699,"Recovered":"" },
		{"Prov":"Odisha","Region":"India","Cases":1049867,"Deaths":8418,"Recovered":"" },
		{"Prov":"Puducherry","Region":"India","Cases":129028,"Deaths":1874,"Recovered":"" },
		{"Prov":"Punjab","Region":"India","Cases":603410,"Deaths":16607,"Recovered":"" },
		{"Prov":"Rajasthan","Region":"India","Cases":954848,"Deaths":8955,"Recovered":"" },
		{"Prov":"Sikkim","Region":"India","Cases":32343,"Deaths":403,"Recovered":"" },
		{"Prov":"Tamil Nadu","Region":"India","Cases":2729061,"Deaths":36513,"Recovered":"" },
		{"Prov":"Telangana","Region":"India","Cases":676574,"Deaths":3997,"Recovered":"" },
		{"Prov":"Tripura","Region":"India","Cases":84844,"Deaths":825,"Recovered":"" },
		{"Prov":"Unknown","Region":"India","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Uttar Pradesh","Region":"India","Cases":1710425,"Deaths":22911,"Recovered":"" },
		{"Prov":"Uttarakhand","Region":"India","Cases":344335,"Deaths":7408,"Recovered":"" },
		{"Prov":"West Bengal","Region":"India","Cases":1618016,"Deaths":19523,"Recovered":"" },
		{"Prov":"Abruzzo","Region":"Italy","Cases":88664,"Deaths":2597,"Recovered":"" },
		{"Prov":"Basilicata","Region":"Italy","Cases":31713,"Deaths":627,"Recovered":"" },
		{"Prov":"Calabria","Region":"Italy","Cases":93891,"Deaths":1503,"Recovered":"" },
		{"Prov":"Campania","Region":"Italy","Cases":494344,"Deaths":8240,"Recovered":"" },
		{"Prov":"Emilia-Romagna","Region":"Italy","Cases":460131,"Deaths":13810,"Recovered":"" },
		{"Prov":"Friuli Venezia Giulia","Region":"Italy","Cases":133351,"Deaths":4008,"Recovered":"" },
		{"Prov":"Lazio","Region":"Italy","Cases":428512,"Deaths":9003,"Recovered":"" },
		{"Prov":"Liguria","Region":"Italy","Cases":124127,"Deaths":4470,"Recovered":"" },
		{"Prov":"Lombardia","Region":"Italy","Cases":940476,"Deaths":34428,"Recovered":"" },
		{"Prov":"Marche","Region":"Italy","Cases":125249,"Deaths":3155,"Recovered":"" },
		{"Prov":"Molise","Region":"Italy","Cases":15265,"Deaths":504,"Recovered":"" },
		{"Prov":"P.A. Bolzano","Region":"Italy","Cases":89880,"Deaths":1247,"Recovered":"" },
		{"Prov":"P.A. Trento","Region":"Italy","Cases":52665,"Deaths":1392,"Recovered":"" },
		{"Prov":"Piemonte","Region":"Italy","Cases":402583,"Deaths":11897,"Recovered":"" },
		{"Prov":"Puglia","Region":"Italy","Cases":280347,"Deaths":6892,"Recovered":"" },
		{"Prov":"Sardegna","Region":"Italy","Cases":79349,"Deaths":1698,"Recovered":"" },
		{"Prov":"Sicilia","Region":"Italy","Cases":326462,"Deaths":7223,"Recovered":"" },
		{"Prov":"Toscana","Region":"Italy","Cases":303379,"Deaths":7418,"Recovered":"" },
		{"Prov":"Umbria","Region":"Italy","Cases":67885,"Deaths":1493,"Recovered":"" },
		{"Prov":"Valle d'Aosta","Region":"Italy","Cases":13369,"Deaths":480,"Recovered":"" },
		{"Prov":"Veneto","Region":"Italy","Cases":525803,"Deaths":11992,"Recovered":"" },
		{"Prov":"Aichi","Region":"Japan","Cases":106904,"Deaths":1161,"Recovered":"" },
		{"Prov":"Akita","Region":"Japan","Cases":1930,"Deaths":27,"Recovered":"" },
		{"Prov":"Aomori","Region":"Japan","Cases":5897,"Deaths":38,"Recovered":"" },
		{"Prov":"Chiba","Region":"Japan","Cases":100479,"Deaths":1028,"Recovered":"" },
		{"Prov":"Ehime","Region":"Japan","Cases":5412,"Deaths":82,"Recovered":"" },
		{"Prov":"Fukui","Region":"Japan","Cases":3115,"Deaths":38,"Recovered":"" },
		{"Prov":"Fukuoka","Region":"Japan","Cases":74637,"Deaths":625,"Recovered":"" },
		{"Prov":"Fukushima","Region":"Japan","Cases":9487,"Deaths":176,"Recovered":"" },
		{"Prov":"Gifu","Region":"Japan","Cases":18920,"Deaths":218,"Recovered":"" },
		{"Prov":"Gunma","Region":"Japan","Cases":16917,"Deaths":176,"Recovered":"" },
		{"Prov":"Hiroshima","Region":"Japan","Cases":22175,"Deaths":202,"Recovered":"" },
		{"Prov":"Hokkaido","Region":"Japan","Cases":61160,"Deaths":1472,"Recovered":"" },
		{"Prov":"Hyogo","Region":"Japan","Cases":78702,"Deaths":1396,"Recovered":"" },
		{"Prov":"Ibaraki","Region":"Japan","Cases":24449,"Deaths":220,"Recovered":"" },
		{"Prov":"Ishikawa","Region":"Japan","Cases":7969,"Deaths":129,"Recovered":"" },
		{"Prov":"Iwate","Region":"Japan","Cases":3487,"Deaths":53,"Recovered":"" },
		{"Prov":"Kagawa","Region":"Japan","Cases":4702,"Deaths":38,"Recovered":"" },
		{"Prov":"Kagoshima","Region":"Japan","Cases":9103,"Deaths":66,"Recovered":"" },
		{"Prov":"Kanagawa","Region":"Japan","Cases":169306,"Deaths":1314,"Recovered":"" },
		{"Prov":"Kochi","Region":"Japan","Cases":4167,"Deaths":33,"Recovered":"" },
		{"Prov":"Kumamoto","Region":"Japan","Cases":14395,"Deaths":136,"Recovered":"" },
		{"Prov":"Kyoto","Region":"Japan","Cases":35995,"Deaths":291,"Recovered":"" },
		{"Prov":"Mie","Region":"Japan","Cases":14814,"Deaths":163,"Recovered":"" },
		{"Prov":"Miyagi","Region":"Japan","Cases":16281,"Deaths":118,"Recovered":"" },
		{"Prov":"Miyazaki","Region":"Japan","Cases":6138,"Deaths":41,"Recovered":"" },
		{"Prov":"Nagano","Region":"Japan","Cases":8885,"Deaths":97,"Recovered":"" },
		{"Prov":"Nagasaki","Region":"Japan","Cases":6119,"Deaths":73,"Recovered":"" },
		{"Prov":"Nara","Region":"Japan","Cases":15647,"Deaths":149,"Recovered":"" },
		{"Prov":"Niigata","Region":"Japan","Cases":8031,"Deaths":61,"Recovered":"" },
		{"Prov":"Oita","Region":"Japan","Cases":8187,"Deaths":84,"Recovered":"" },
		{"Prov":"Okayama","Region":"Japan","Cases":15543,"Deaths":136,"Recovered":"" },
		{"Prov":"Okinawa","Region":"Japan","Cases":50322,"Deaths":398,"Recovered":"" },
		{"Prov":"Osaka","Region":"Japan","Cases":203183,"Deaths":3064,"Recovered":"" },
		{"Prov":"Port Quarantine","Region":"Japan","Cases":4463,"Deaths":4,"Recovered":"" },
		{"Prov":"Saga","Region":"Japan","Cases":5866,"Deaths":30,"Recovered":"" },
		{"Prov":"Saitama","Region":"Japan","Cases":115867,"Deaths":1057,"Recovered":"" },
		{"Prov":"Shiga","Region":"Japan","Cases":12433,"Deaths":104,"Recovered":"" },
		{"Prov":"Shimane","Region":"Japan","Cases":1733,"Deaths":5,"Recovered":"" },
		{"Prov":"Shizuoka","Region":"Japan","Cases":26797,"Deaths":209,"Recovered":"" },
		{"Prov":"Tochigi","Region":"Japan","Cases":15487,"Deaths":117,"Recovered":"" },
		{"Prov":"Tokushima","Region":"Japan","Cases":3291,"Deaths":66,"Recovered":"" },
		{"Prov":"Tokyo","Region":"Japan","Cases":382221,"Deaths":3168,"Recovered":"" },
		{"Prov":"Tottori","Region":"Japan","Cases":1669,"Deaths":5,"Recovered":"" },
		{"Prov":"Toyama","Region":"Japan","Cases":4868,"Deaths":52,"Recovered":"" },
		{"Prov":"Unknown","Region":"Japan","Cases":8,"Deaths":0,"Recovered":"" },
		{"Prov":"Wakayama","Region":"Japan","Cases":5303,"Deaths":62,"Recovered":"" },
		{"Prov":"Yamagata","Region":"Japan","Cases":3593,"Deaths":56,"Recovered":"" },
		{"Prov":"Yamaguchi","Region":"Japan","Cases":5792,"Deaths":93,"Recovered":"" },
		{"Prov":"Yamanashi","Region":"Japan","Cases":5156,"Deaths":29,"Recovered":"" },
		{"Prov":"Johor","Region":"Malaysia","Cases":233507,"Deaths":3778,"Recovered":"" },
		{"Prov":"Kedah","Region":"Malaysia","Cases":160918,"Deaths":2092,"Recovered":"" },
		{"Prov":"Kelantan","Region":"Malaysia","Cases":158258,"Deaths":1179,"Recovered":"" },
		{"Prov":"Melaka","Region":"Malaysia","Cases":71674,"Deaths":939,"Recovered":"" },
		{"Prov":"Negeri Sembilan","Region":"Malaysia","Cases":109177,"Deaths":1278,"Recovered":"" },
		{"Prov":"Pahang","Region":"Malaysia","Cases":87625,"Deaths":716,"Recovered":"" },
		{"Prov":"Perak","Region":"Malaysia","Cases":123681,"Deaths":1272,"Recovered":"" },
		{"Prov":"Perlis","Region":"Malaysia","Cases":6470,"Deaths":126,"Recovered":"" },
		{"Prov":"Pulau Pinang","Region":"Malaysia","Cases":154035,"Deaths":1659,"Recovered":"" },
		{"Prov":"Sabah","Region":"Malaysia","Cases":234501,"Deaths":2698,"Recovered":"" },
		{"Prov":"Sarawak","Region":"Malaysia","Cases":251038,"Deaths":1591,"Recovered":"" },
		{"Prov":"Selangor","Region":"Malaysia","Cases":758500,"Deaths":9811,"Recovered":"" },
		{"Prov":"Terengganu","Region":"Malaysia","Cases":77116,"Deaths":607,"Recovered":"" },
		{"Prov":"Unknown","Region":"Malaysia","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"W.P. Kuala Lumpur","Region":"Malaysia","Cases":203923,"Deaths":2621,"Recovered":"" },
		{"Prov":"W.P. Labuan","Region":"Malaysia","Cases":10529,"Deaths":150,"Recovered":"" },
		{"Prov":"W.P. Putrajaya","Region":"Malaysia","Cases":8626,"Deaths":21,"Recovered":"" },
		{"Prov":"Aguascalientes","Region":"Mexico","Cases":37363,"Deaths":2946,"Recovered":"" },
		{"Prov":"Baja California","Region":"Mexico","Cases":82361,"Deaths":10418,"Recovered":"" },
		{"Prov":"Baja California Sur","Region":"Mexico","Cases":57174,"Deaths":2396,"Recovered":"" },
		{"Prov":"Campeche","Region":"Mexico","Cases":24204,"Deaths":2096,"Recovered":"" },
		{"Prov":"Chiapas","Region":"Mexico","Cases":23531,"Deaths":2283,"Recovered":"" },
		{"Prov":"Chihuahua","Region":"Mexico","Cases":74083,"Deaths":8335,"Recovered":"" },
		{"Prov":"Ciudad de Mexico","Region":"Mexico","Cases":986081,"Deaths":40176,"Recovered":"" },
		{"Prov":"Coahuila","Region":"Mexico","Cases":98417,"Deaths":7622,"Recovered":"" },
		{"Prov":"Colima","Region":"Mexico","Cases":33330,"Deaths":2036,"Recovered":"" },
		{"Prov":"Durango","Region":"Mexico","Cases":49960,"Deaths":3102,"Recovered":"" },
		{"Prov":"Guanajuato","Region":"Mexico","Cases":197244,"Deaths":13041,"Recovered":"" },
		{"Prov":"Guerrero","Region":"Mexico","Cases":77082,"Deaths":6257,"Recovered":"" },
		{"Prov":"Hidalgo","Region":"Mexico","Cases":62745,"Deaths":7866,"Recovered":"" },
		{"Prov":"Jalisco","Region":"Mexico","Cases":163698,"Deaths":17615,"Recovered":"" },
		{"Prov":"Mexico","Region":"Mexico","Cases":379477,"Deaths":44412,"Recovered":"" },
		{"Prov":"Michoacan","Region":"Mexico","Cases":73654,"Deaths":8216,"Recovered":"" },
		{"Prov":"Morelos","Region":"Mexico","Cases":50477,"Deaths":4935,"Recovered":"" },
		{"Prov":"Nayarit","Region":"Mexico","Cases":34253,"Deaths":2876,"Recovered":"" },
		{"Prov":"Nuevo Leon","Region":"Mexico","Cases":207284,"Deaths":13547,"Recovered":"" },
		{"Prov":"Oaxaca","Region":"Mexico","Cases":83325,"Deaths":5604,"Recovered":"" },
		{"Prov":"Puebla","Region":"Mexico","Cases":125854,"Deaths":15533,"Recovered":"" },
		{"Prov":"Queretaro","Region":"Mexico","Cases":99269,"Deaths":5614,"Recovered":"" },
		{"Prov":"Quintana Roo","Region":"Mexico","Cases":59836,"Deaths":4077,"Recovered":"" },
		{"Prov":"San Luis Potosi","Region":"Mexico","Cases":105544,"Deaths":6720,"Recovered":"" },
		{"Prov":"Sinaloa","Region":"Mexico","Cases":74684,"Deaths":8853,"Recovered":"" },
		{"Prov":"Sonora","Region":"Mexico","Cases":118679,"Deaths":8766,"Recovered":"" },
		{"Prov":"Tabasco","Region":"Mexico","Cases":143771,"Deaths":5647,"Recovered":"" },
		{"Prov":"Tamaulipas","Region":"Mexico","Cases":103239,"Deaths":6972,"Recovered":"" },
		{"Prov":"Tlaxcala","Region":"Mexico","Cases":29478,"Deaths":2992,"Recovered":"" },
		{"Prov":"Unknown","Region":"Mexico","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Veracruz","Region":"Mexico","Cases":124001,"Deaths":14846,"Recovered":"" },
		{"Prov":"Yucatan","Region":"Mexico","Cases":75226,"Deaths":5692,"Recovered":"" },
		{"Prov":"Zacatecas","Region":"Mexico","Cases":42128,"Deaths":3413,"Recovered":"" },
		{"Prov":"Aruba","Region":"Netherlands","Cases":16414,"Deaths":174,"Recovered":"" },
		{"Prov":"*Bonaire, Sint Eustatius and Saba*","Region":"Netherlands","Cases":3026,"Deaths":22,"Recovered":"" },
		{"Prov":"Curacao","Region":"Netherlands","Cases":17455,"Deaths":179,"Recovered":"" },
		{"Prov":"Drenthe","Region":"Netherlands","Cases":53847,"Deaths":392,"Recovered":"" },
		{"Prov":"Flevoland","Region":"Netherlands","Cases":61701,"Deaths":280,"Recovered":"" },
		{"Prov":"Friesland","Region":"Netherlands","Cases":80905,"Deaths":524,"Recovered":"" },
		{"Prov":"Gelderland","Region":"Netherlands","Cases":310566,"Deaths":2373,"Recovered":"" },
		{"Prov":"Groningen","Region":"Netherlands","Cases":64968,"Deaths":302,"Recovered":"" },
		{"Prov":"Limburg","Region":"Netherlands","Cases":198476,"Deaths":1899,"Recovered":"" },
		{"Prov":"Noord-Brabant","Region":"Netherlands","Cases":415608,"Deaths":3371,"Recovered":"" },
		{"Prov":"Noord-Holland","Region":"Netherlands","Cases":445554,"Deaths":2892,"Recovered":"" },
		{"Prov":"Overijssel","Region":"Netherlands","Cases":176764,"Deaths":1263,"Recovered":"" },
		{"Prov":"Sint Maarten","Region":"Netherlands","Cases":4594,"Deaths":75,"Recovered":"" },
		{"Prov":"Unknown","Region":"Netherlands","Cases":11471,"Deaths":15,"Recovered":"" },
		{"Prov":"Utrecht","Region":"Netherlands","Cases":211043,"Deaths":1361,"Recovered":"" },
		{"Prov":"Zeeland","Region":"Netherlands","Cases":53434,"Deaths":282,"Recovered":"" },
		{"Prov":"Zuid-Holland","Region":"Netherlands","Cases":621926,"Deaths":4632,"Recovered":"" },
		{"Prov":"Cook Islands","Region":"New Zealand","Cases":1,"Deaths":0,"Recovered":"" },
		{"Prov":"Azad Jammu and Kashmir","Region":"Pakistan","Cases":34574,"Deaths":742,"Recovered":"" },
		{"Prov":"Balochistan","Region":"Pakistan","Cases":33491,"Deaths":360,"Recovered":"" },
		{"Prov":"Gilgit-Baltistan","Region":"Pakistan","Cases":10413,"Deaths":186,"Recovered":"" },
		{"Prov":"Islamabad","Region":"Pakistan","Cases":107848,"Deaths":958,"Recovered":"" },
		{"Prov":"Khyber Pakhtunkhwa","Region":"Pakistan","Cases":180254,"Deaths":5858,"Recovered":"" },
		{"Prov":"Punjab","Region":"Pakistan","Cases":443379,"Deaths":13035,"Recovered":"" },
		{"Prov":"Sindh","Region":"Pakistan","Cases":476494,"Deaths":7622,"Recovered":"" },
		{"Prov":"Amazonas","Region":"Peru","Cases":32177,"Deaths":1269,"Recovered":"" },
		{"Prov":"Ancash","Region":"Peru","Cases":79129,"Deaths":6713,"Recovered":"" },
		{"Prov":"Apurimac","Region":"Peru","Cases":26543,"Deaths":1516,"Recovered":"" },
		{"Prov":"Arequipa","Region":"Peru","Cases":116285,"Deaths":9706,"Recovered":"" },
		{"Prov":"Ayacucho","Region":"Peru","Cases":34631,"Deaths":2137,"Recovered":"" },
		{"Prov":"Cajamarca","Region":"Peru","Cases":66513,"Deaths":4142,"Recovered":"" },
		{"Prov":"Callao","Region":"Peru","Cases":102468,"Deaths":10033,"Recovered":"" },
		{"Prov":"Cusco","Region":"Peru","Cases":74968,"Deaths":4800,"Recovered":"" },
		{"Prov":"Huancavelica","Region":"Peru","Cases":16377,"Deaths":1172,"Recovered":"" },
		{"Prov":"Huanuco","Region":"Peru","Cases":36037,"Deaths":2696,"Recovered":"" },
		{"Prov":"Ica","Region":"Peru","Cases":60162,"Deaths":8557,"Recovered":"" },
		{"Prov":"Junin","Region":"Peru","Cases":87848,"Deaths":7049,"Recovered":"" },
		{"Prov":"La Libertad","Region":"Peru","Cases":90973,"Deaths":10285,"Recovered":"" },
		{"Prov":"Lambayeque","Region":"Peru","Cases":62961,"Deaths":8629,"Recovered":"" },
		{"Prov":"Lima","Region":"Peru","Cases":977690,"Deaths":88865,"Recovered":"" },
		{"Prov":"Loreto","Region":"Peru","Cases":45236,"Deaths":4268,"Recovered":"" },
		{"Prov":"Madre de Dios","Region":"Peru","Cases":13993,"Deaths":771,"Recovered":"" },
		{"Prov":"Moquegua","Region":"Peru","Cases":29840,"Deaths":1524,"Recovered":"" },
		{"Prov":"Pasco","Region":"Peru","Cases":16063,"Deaths":1047,"Recovered":"" },
		{"Prov":"Piura","Region":"Peru","Cases":91570,"Deaths":12101,"Recovered":"" },
		{"Prov":"Puno","Region":"Peru","Cases":41423,"Deaths":4210,"Recovered":"" },
		{"Prov":"San Martin","Region":"Peru","Cases":49044,"Deaths":3023,"Recovered":"" },
		{"Prov":"Tacna","Region":"Peru","Cases":30698,"Deaths":1963,"Recovered":"" },
		{"Prov":"Tumbes","Region":"Peru","Cases":19246,"Deaths":1582,"Recovered":"" },
		{"Prov":"Ucayali","Region":"Peru","Cases":32200,"Deaths":3050,"Recovered":"" },
		{"Prov":"Unknown","Region":"Peru","Cases":6952,"Deaths":218,"Recovered":"" },
		{"Prov":"Adygea Republic","Region":"Russia","Cases":24484,"Deaths":670,"Recovered":"" },
		{"Prov":"Altai Krai","Region":"Russia","Cases":105613,"Deaths":5833,"Recovered":"" },
		{"Prov":"Altai Republic","Region":"Russia","Cases":24443,"Deaths":467,"Recovered":"" },
		{"Prov":"Amur Oblast","Region":"Russia","Cases":47286,"Deaths":539,"Recovered":"" },
		{"Prov":"Arkhangelsk Oblast","Region":"Russia","Cases":114791,"Deaths":1353,"Recovered":"" },
		{"Prov":"Astrakhan Oblast","Region":"Russia","Cases":74723,"Deaths":2206,"Recovered":"" },
		{"Prov":"Bashkortostan Republic","Region":"Russia","Cases":108356,"Deaths":3654,"Recovered":"" },
		{"Prov":"Belgorod Oblast","Region":"Russia","Cases":73849,"Deaths":1556,"Recovered":"" },
		{"Prov":"Bryansk Oblast","Region":"Russia","Cases":90265,"Deaths":2355,"Recovered":"" },
		{"Prov":"Buryatia Republic","Region":"Russia","Cases":70233,"Deaths":2209,"Recovered":"" },
		{"Prov":"Chechen Republic","Region":"Russia","Cases":28831,"Deaths":843,"Recovered":"" },
		{"Prov":"Chelyabinsk Oblast","Region":"Russia","Cases":128771,"Deaths":5229,"Recovered":"" },
		{"Prov":"Chukotka Autonomous Okrug","Region":"Russia","Cases":2866,"Deaths":27,"Recovered":"" },
		{"Prov":"Chuvashia Republic","Region":"Russia","Cases":43407,"Deaths":3359,"Recovered":"" },
		{"Prov":"Dagestan Republic","Region":"Russia","Cases":61844,"Deaths":2991,"Recovered":"" },
		{"Prov":"Ingushetia Republic","Region":"Russia","Cases":26401,"Deaths":428,"Recovered":"" },
		{"Prov":"Irkutsk Oblast","Region":"Russia","Cases":140536,"Deaths":6284,"Recovered":"" },
		{"Prov":"Ivanovo Oblast","Region":"Russia","Cases":62658,"Deaths":2169,"Recovered":"" },
		{"Prov":"Jewish Autonomous Okrug","Region":"Russia","Cases":10675,"Deaths":344,"Recovered":"" },
		{"Prov":"Kabardino-Balkarian Republic","Region":"Russia","Cases":39253,"Deaths":1215,"Recovered":"" },
		{"Prov":"Kaliningrad Oblast","Region":"Russia","Cases":76659,"Deaths":1058,"Recovered":"" },
		{"Prov":"Kalmykia Republic","Region":"Russia","Cases":33508,"Deaths":698,"Recovered":"" },
		{"Prov":"Kaluga Oblast","Region":"Russia","Cases":59804,"Deaths":1051,"Recovered":"" },
		{"Prov":"Kamchatka Krai","Region":"Russia","Cases":22550,"Deaths":484,"Recovered":"" },
		{"Prov":"Karachay-Cherkess Republic","Region":"Russia","Cases":30329,"Deaths":873,"Recovered":"" },
		{"Prov":"Karelia Republic","Region":"Russia","Cases":83886,"Deaths":1086,"Recovered":"" },
		{"Prov":"Kemerovo Oblast","Region":"Russia","Cases":75142,"Deaths":1587,"Recovered":"" },
		{"Prov":"Khabarovsk Krai","Region":"Russia","Cases":111692,"Deaths":1075,"Recovered":"" },
		{"Prov":"Khakassia Republic","Region":"Russia","Cases":50254,"Deaths":1658,"Recovered":"" },
		{"Prov":"Khanty-Mansi Autonomous Okrug","Region":"Russia","Cases":90396,"Deaths":1749,"Recovered":"" },
		{"Prov":"Kirov Oblast","Region":"Russia","Cases":72385,"Deaths":685,"Recovered":"" },
		{"Prov":"Komi Republic","Region":"Russia","Cases":90842,"Deaths":2326,"Recovered":"" },
		{"Prov":"Kostroma Oblast","Region":"Russia","Cases":45189,"Deaths":990,"Recovered":"" },
		{"Prov":"Krasnodar Krai","Region":"Russia","Cases":101185,"Deaths":9030,"Recovered":"" },
		{"Prov":"Krasnoyarsk Krai","Region":"Russia","Cases":154858,"Deaths":7595,"Recovered":"" },
		{"Prov":"Kurgan Oblast","Region":"Russia","Cases":45653,"Deaths":890,"Recovered":"" },
		{"Prov":"Kursk Oblast","Region":"Russia","Cases":77416,"Deaths":1821,"Recovered":"" },
		{"Prov":"Leningrad Oblast","Region":"Russia","Cases":91581,"Deaths":2809,"Recovered":"" },
		{"Prov":"Lipetsk Oblast","Region":"Russia","Cases":75747,"Deaths":2465,"Recovered":"" },
		{"Prov":"Magadan Oblast","Region":"Russia","Cases":12888,"Deaths":316,"Recovered":"" },
		{"Prov":"Mari El Republic","Region":"Russia","Cases":26665,"Deaths":790,"Recovered":"" },
		{"Prov":"Mordovia Republic","Region":"Russia","Cases":37118,"Deaths":905,"Recovered":"" },
		{"Prov":"Moscow","Region":"Russia","Cases":1956583,"Deaths":34483,"Recovered":"" },
		{"Prov":"Moscow Oblast","Region":"Russia","Cases":594862,"Deaths":10601,"Recovered":"" },
		{"Prov":"Murmansk Oblast","Region":"Russia","Cases":87224,"Deaths":2577,"Recovered":"" },
		{"Prov":"Nenets Autonomous Okrug","Region":"Russia","Cases":3254,"Deaths":80,"Recovered":"" },
		{"Prov":"Nizhny Novgorod Oblast","Region":"Russia","Cases":216427,"Deaths":8986,"Recovered":"" },
		{"Prov":"North Ossetia - Alania Republic","Region":"Russia","Cases":28774,"Deaths":772,"Recovered":"" },
		{"Prov":"Novgorod Oblast","Region":"Russia","Cases":60271,"Deaths":635,"Recovered":"" },
		{"Prov":"Novosibirsk Oblast","Region":"Russia","Cases":83921,"Deaths":3845,"Recovered":"" },
		{"Prov":"Omsk Oblast","Region":"Russia","Cases":116307,"Deaths":2863,"Recovered":"" },
		{"Prov":"Orel Oblast","Region":"Russia","Cases":64197,"Deaths":1314,"Recovered":"" },
		{"Prov":"Orenburg Oblast","Region":"Russia","Cases":101955,"Deaths":3194,"Recovered":"" },
		{"Prov":"Penza Oblast","Region":"Russia","Cases":92906,"Deaths":4277,"Recovered":"" },
		{"Prov":"Perm Krai","Region":"Russia","Cases":142848,"Deaths":6910,"Recovered":"" },
		{"Prov":"Primorsky Krai","Region":"Russia","Cases":89396,"Deaths":1416,"Recovered":"" },
		{"Prov":"Pskov Oblast","Region":"Russia","Cases":66557,"Deaths":1098,"Recovered":"" },
		{"Prov":"Rostov Oblast","Region":"Russia","Cases":177498,"Deaths":8832,"Recovered":"" },
		{"Prov":"Ryazan Oblast","Region":"Russia","Cases":56170,"Deaths":2026,"Recovered":"" },
		{"Prov":"Saint Petersburg","Region":"Russia","Cases":794923,"Deaths":26380,"Recovered":"" },
		{"Prov":"Sakha (Yakutiya) Republic","Region":"Russia","Cases":71224,"Deaths":1700,"Recovered":"" },
		{"Prov":"Sakhalin Oblast","Region":"Russia","Cases":38166,"Deaths":451,"Recovered":"" },
		{"Prov":"Samara Oblast","Region":"Russia","Cases":182533,"Deaths":5596,"Recovered":"" },
		{"Prov":"Saratov Oblast","Region":"Russia","Cases":122013,"Deaths":4681,"Recovered":"" },
		{"Prov":"Smolensk Oblast","Region":"Russia","Cases":79039,"Deaths":2161,"Recovered":"" },
		{"Prov":"Stavropol Krai","Region":"Russia","Cases":114252,"Deaths":5316,"Recovered":"" },
		{"Prov":"Sverdlovsk Oblast","Region":"Russia","Cases":181368,"Deaths":8525,"Recovered":"" },
		{"Prov":"Tambov Oblast","Region":"Russia","Cases":55283,"Deaths":1451,"Recovered":"" },
		{"Prov":"Tatarstan Republic","Region":"Russia","Cases":38760,"Deaths":1276,"Recovered":"" },
		{"Prov":"Tomsk Oblast","Region":"Russia","Cases":56539,"Deaths":635,"Recovered":"" },
		{"Prov":"Tula Oblast","Region":"Russia","Cases":68699,"Deaths":3933,"Recovered":"" },
		{"Prov":"Tver Oblast","Region":"Russia","Cases":89500,"Deaths":2140,"Recovered":"" },
		{"Prov":"Tyumen Oblast","Region":"Russia","Cases":81812,"Deaths":2916,"Recovered":"" },
		{"Prov":"Tyva Republic","Region":"Russia","Cases":30764,"Deaths":305,"Recovered":"" },
		{"Prov":"Udmurt Republic","Region":"Russia","Cases":75473,"Deaths":3083,"Recovered":"" },
		{"Prov":"Ulyanovsk Oblast","Region":"Russia","Cases":112380,"Deaths":3427,"Recovered":"" },
		{"Prov":"Vladimir Oblast","Region":"Russia","Cases":73384,"Deaths":2625,"Recovered":"" },
		{"Prov":"Volgograd Oblast","Region":"Russia","Cases":119144,"Deaths":4684,"Recovered":"" },
		{"Prov":"Vologda Oblast","Region":"Russia","Cases":91244,"Deaths":2618,"Recovered":"" },
		{"Prov":"Voronezh Oblast","Region":"Russia","Cases":179488,"Deaths":5889,"Recovered":"" },
		{"Prov":"Yamalo-Nenets Autonomous Okrug","Region":"Russia","Cases":58836,"Deaths":875,"Recovered":"" },
		{"Prov":"Yaroslavl Oblast","Region":"Russia","Cases":78238,"Deaths":1565,"Recovered":"" },
		{"Prov":"Zabaykalsky Krai","Region":"Russia","Cases":88665,"Deaths":1650,"Recovered":"" },
		{"Prov":"Andalusia","Region":"Spain","Cases":826194,"Deaths":11350,"Recovered":"" },
		{"Prov":"Aragon","Region":"Spain","Cases":172063,"Deaths":3960,"Recovered":"" },
		{"Prov":"Asturias","Region":"Spain","Cases":74920,"Deaths":2094,"Recovered":"" },
		{"Prov":"Baleares","Region":"Spain","Cases":106848,"Deaths":1025,"Recovered":"" },
		{"Prov":"C. Valenciana","Region":"Spain","Cases":537178,"Deaths":7913,"Recovered":"" },
		{"Prov":"Canarias","Region":"Spain","Cases":104886,"Deaths":1055,"Recovered":"" },
		{"Prov":"Cantabria","Region":"Spain","Cases":48646,"Deaths":616,"Recovered":"" },
		{"Prov":"Castilla - La Mancha","Region":"Spain","Cases":245805,"Deaths":6537,"Recovered":"" },
		{"Prov":"Castilla y Leon","Region":"Spain","Cases":312769,"Deaths":7428,"Recovered":"" },
		{"Prov":"Catalonia","Region":"Spain","Cases":970334,"Deaths":16035,"Recovered":"" },
		{"Prov":"Ceuta","Region":"Spain","Cases":7739,"Deaths":130,"Recovered":"" },
		{"Prov":"Extremadura","Region":"Spain","Cases":105208,"Deaths":1999,"Recovered":"" },
		{"Prov":"Galicia","Region":"Spain","Cases":196638,"Deaths":2674,"Recovered":"" },
		{"Prov":"La Rioja","Region":"Spain","Cases":41008,"Deaths":830,"Recovered":"" },
		{"Prov":"Madrid","Region":"Spain","Cases":918911,"Deaths":16302,"Recovered":"" },
		{"Prov":"Melilla","Region":"Spain","Cases":11365,"Deaths":113,"Recovered":"" },
		{"Prov":"Murcia","Region":"Spain","Cases":148549,"Deaths":1768,"Recovered":"" },
		{"Prov":"Navarra","Region":"Spain","Cases":90457,"Deaths":1266,"Recovered":"" },
		{"Prov":"Pais Vasco","Region":"Spain","Cases":283440,"Deaths":5064,"Recovered":"" },
		{"Prov":"Unknown","Region":"Spain","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Blekinge","Region":"Sweden","Cases":14158,"Deaths":131,"Recovered":"" },
		{"Prov":"Dalarna","Region":"Sweden","Cases":29518,"Deaths":359,"Recovered":"" },
		{"Prov":"Gavleborg","Region":"Sweden","Cases":38964,"Deaths":566,"Recovered":"" },
		{"Prov":"Gotland","Region":"Sweden","Cases":4754,"Deaths":54,"Recovered":"" },
		{"Prov":"Halland","Region":"Sweden","Cases":44945,"Deaths":329,"Recovered":"" },
		{"Prov":"Jamtland Harjedalen","Region":"Sweden","Cases":13515,"Deaths":128,"Recovered":"" },
		{"Prov":"Jonkoping","Region":"Sweden","Cases":46645,"Deaths":567,"Recovered":"" },
		{"Prov":"Kalmar","Region":"Sweden","Cases":26950,"Deaths":255,"Recovered":"" },
		{"Prov":"Kronoberg","Region":"Sweden","Cases":24076,"Deaths":328,"Recovered":"" },
		{"Prov":"Norrbotten","Region":"Sweden","Cases":28826,"Deaths":295,"Recovered":"" },
		{"Prov":"Orebro","Region":"Sweden","Cases":36305,"Deaths":355,"Recovered":"" },
		{"Prov":"Ostergotland","Region":"Sweden","Cases":45820,"Deaths":661,"Recovered":"" },
		{"Prov":"Skane","Region":"Sweden","Cases":172702,"Deaths":1814,"Recovered":"" },
		{"Prov":"Sormland","Region":"Sweden","Cases":28584,"Deaths":485,"Recovered":"" },
		{"Prov":"Stockholm","Region":"Sweden","Cases":290360,"Deaths":4533,"Recovered":"" },
		{"Prov":"Uppsala","Region":"Sweden","Cases":44594,"Deaths":550,"Recovered":"" },
		{"Prov":"Varmland","Region":"Sweden","Cases":22652,"Deaths":228,"Recovered":"" },
		{"Prov":"Vasterbotten","Region":"Sweden","Cases":27201,"Deaths":202,"Recovered":"" },
		{"Prov":"Vasternorrland","Region":"Sweden","Cases":28563,"Deaths":488,"Recovered":"" },
		{"Prov":"Vastmanland","Region":"Sweden","Cases":33429,"Deaths":375,"Recovered":"" },
		{"Prov":"Vastra Gotaland","Region":"Sweden","Cases":209584,"Deaths":2467,"Recovered":"" },
		{"Prov":"Cherkasy Oblast","Region":"Ukraine","Cases":119699,"Deaths":2277,"Recovered":"" },
		{"Prov":"Chernihiv Oblast","Region":"Ukraine","Cases":90046,"Deaths":2168,"Recovered":"" },
		{"Prov":"Chernivtsi Oblast","Region":"Ukraine","Cases":116285,"Deaths":2845,"Recovered":"" },
		{"Prov":"Crimea Republic*","Region":"Ukraine","Cases":120758,"Deaths":3681,"Recovered":"" },
		{"Prov":"Dnipropetrovsk Oblast","Region":"Ukraine","Cases":234210,"Deaths":8026,"Recovered":"" },
		{"Prov":"Donetsk Oblast","Region":"Ukraine","Cases":156483,"Deaths":4639,"Recovered":"" },
		{"Prov":"Ivano-Frankivsk Oblast","Region":"Ukraine","Cases":122046,"Deaths":2898,"Recovered":"" },
		{"Prov":"Kharkiv Oblast","Region":"Ukraine","Cases":236469,"Deaths":5790,"Recovered":"" },
		{"Prov":"Kherson Oblast","Region":"Ukraine","Cases":76798,"Deaths":2527,"Recovered":"" },
		{"Prov":"Khmelnytskyi Oblast","Region":"Ukraine","Cases":139434,"Deaths":3012,"Recovered":"" },
		{"Prov":"Kiev","Region":"Ukraine","Cases":303205,"Deaths":7620,"Recovered":"" },
		{"Prov":"Kiev Oblast","Region":"Ukraine","Cases":175563,"Deaths":4264,"Recovered":"" },
		{"Prov":"Kirovohrad Oblast","Region":"Ukraine","Cases":30005,"Deaths":1267,"Recovered":"" },
		{"Prov":"Luhansk Oblast","Region":"Ukraine","Cases":57624,"Deaths":2019,"Recovered":"" },
		{"Prov":"Lviv Oblast","Region":"Ukraine","Cases":210867,"Deaths":5538,"Recovered":"" },
		{"Prov":"Mykolaiv Oblast","Region":"Ukraine","Cases":109174,"Deaths":3063,"Recovered":"" },
		{"Prov":"Odessa Oblast","Region":"Ukraine","Cases":229612,"Deaths":5254,"Recovered":"" },
		{"Prov":"Poltava Oblast","Region":"Ukraine","Cases":128251,"Deaths":3276,"Recovered":"" },
		{"Prov":"Rivne Oblast","Region":"Ukraine","Cases":121823,"Deaths":2082,"Recovered":"" },
		{"Prov":"Sevastopol*","Region":"Ukraine","Cases":49370,"Deaths":1713,"Recovered":"" },
		{"Prov":"Sumy Oblast","Region":"Ukraine","Cases":126120,"Deaths":2605,"Recovered":"" },
		{"Prov":"Ternopil Oblast","Region":"Ukraine","Cases":102977,"Deaths":1968,"Recovered":"" },
		{"Prov":"Vinnytsia Oblast","Region":"Ukraine","Cases":105744,"Deaths":2767,"Recovered":"" },
		{"Prov":"Volyn Oblast","Region":"Ukraine","Cases":95664,"Deaths":2001,"Recovered":"" },
		{"Prov":"Zakarpattia Oblast","Region":"Ukraine","Cases":81482,"Deaths":2079,"Recovered":"" },
		{"Prov":"Zaporizhia Oblast","Region":"Ukraine","Cases":173251,"Deaths":4545,"Recovered":"" },
		{"Prov":"Zhytomyr Oblast","Region":"Ukraine","Cases":134817,"Deaths":3036,"Recovered":"" },
		{"Prov":"Anguilla","Region":"United Kingdom","Cases":1414,"Deaths":3,"Recovered":"" },
		{"Prov":"Bermuda","Region":"United Kingdom","Cases":5751,"Deaths":106,"Recovered":"" },
		{"Prov":"British Virgin Islands","Region":"United Kingdom","Cases":2809,"Deaths":38,"Recovered":"" },
		{"Prov":"Cayman Islands","Region":"United Kingdom","Cases":7529,"Deaths":7,"Recovered":"" },
		{"Prov":"Channel Islands","Region":"United Kingdom","Cases":18893,"Deaths":104,"Recovered":"" },
		{"Prov":"England","Region":"United Kingdom","Cases":8802632,"Deaths":126477,"Recovered":"" },
		{"Prov":"Falkland Islands (Malvinas)","Region":"United Kingdom","Cases":83,"Deaths":0,"Recovered":"" },
		{"Prov":"Gibraltar","Region":"United Kingdom","Cases":7340,"Deaths":99,"Recovered":"" },
		{"Prov":"Isle of Man","Region":"United Kingdom","Cases":11764,"Deaths":67,"Recovered":"" },
		{"Prov":"Montserrat","Region":"United Kingdom","Cases":44,"Deaths":1,"Recovered":"" },
		{"Prov":"Northern Ireland","Region":"United Kingdom","Cases":325119,"Deaths":2885,"Recovered":"" },
		{"Prov":"*Saint Helena, Ascension and Tristan da Cunha*","Region":"United Kingdom","Cases":4,"Deaths":0,"Recovered":"" },
		{"Prov":"Scotland","Region":"United Kingdom","Cases":735750,"Deaths":9634,"Recovered":"" },
		{"Prov":"Turks and Caicos Islands","Region":"United Kingdom","Cases":3103,"Deaths":25,"Recovered":"" },
		{"Prov":"Unknown","Region":"United Kingdom","Cases":0,"Deaths":0,"Recovered":"" },
		{"Prov":"Wales","Region":"United Kingdom","Cases":516146,"Deaths":6428,"Recovered":"" }
		]}
